project:
  type: website
  output-dir: docs

website:
  title: "**Stats-blog**"
  description: "A blog about PSY-504"
  navbar:
    left: 
      - text: Home
        href: about.qmd
    right:
      - about.qmd
      - icon: github
        href: https://github.com/scm1210
      - icon: twitter
        href: https://x.com/StevenMesquiti
      - icon: google scholar 
        href: https://scholar.google.com/citations?user=0Y1Y1aMAAAAJ&hl=en
format:
  html:
    theme:
      - cyborg
      - brand
    toc: true                     # Show a table of contents on pages
    css: styles.css

editor: visual

