{
  "hash": "bf87d2df0b90c5442a852f7a2364d190",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Poisson Lab Answers\"\nsubtitle: \"Princeton University\"\nauthor: \"Steven Mesquiti\"\noutput: \n  tufte::tufte_html:\n    css: \n    tufte_variant: \"envisioned\"\n    highlight: github-dark\n    fig_height: 10\n    fig_width: 16\n    toc: true\n    toc_depth: 1\nexecute: \n  message: false\n  warning: false\nformat: html\nengine: knitr\n---\n\n\n\n1.  To complete this lab:\n\n-   Load packages\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(pacman)\npacman::p_load(MASS,tidyverse,emmeans,ggeffects,easystats,performance,knitr, naniar,skimr,install = T)\n\n\npalette <- c(\n  \"#772e25\", \"#c44536\", \"#ee9b00\", \"#197278\", \"#283d3b\", \n  \"#9CC5A1\", \"#6195C6\", \"#ADA7C9\", \"#4D4861\", \"grey50\",\n  \"#d4a373\", \"#8a5a44\", \"#4a6a74\", \"#5c80a8\", \"#a9c5a0\",\n  \"#7b9b8e\", \"#e1b16a\", \"#a69b7c\", \"#9d94c4\", \"#665c54\"\n)\n\npalette_condition = c(\"#ee9b00\", \"#c44536\",\"#005f73\", \"#283d3b\", \"#9CC5A1\", \"#6195C6\", \"#ADA7C9\", \"#4D4861\")\n\nplot_aes = theme_minimal() +\n  theme(\n    legend.position = \"top\",\n    legend.text = element_text(size = 12),\n    text = element_text(size = 16, family = \"Futura Medium\"),\n    axis.text = element_text(color = \"black\"),\n    axis.ticks.y = element_blank(),\n    plot.title = element_text(size = 20, hjust = 0.5) # Adjusted title size and centering\n  )\n```\n:::\n\n\n\n-   Download the dataset:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata <- read_delim(\"https://raw.githubusercontent.com/jgeller112/psy504-advanced-stats/main/slides/Poisson/data/2010.csv\")\n\ndata |> \n  head() |> \n  DT::datatable()\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"datatables html-widget html-fill-item\" id=\"htmlwidget-7b9a75698ce6a3b86eec\" style=\"width:100%;height:auto;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-7b9a75698ce6a3b86eec\">{\"x\":{\"filter\":\"none\",\"vertical\":false,\"data\":[[\"1\",\"2\",\"3\",\"4\",\"5\",\"6\"],[5,5,4,2,1,5],[0,0,0,0,1,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,2,0,9,0],[0,0,1,0,9,0],[0,0,8,0,2,0],[0,0,2,0,2,0],[0,0,2,0,2,0],[0,0,1,0,2,0],[0,0,2,0,2,0],[2,1,0,9,0,0],[1,1,1,1,2,1],[0,0,0,0,2,0],[4,1,4,4,0,2],[31,23,71,82,78,40],[1,3,0,1,1,3],[0,0,21,19,22,24],[0,0,0,0,2,0],[0,0,0,0,3,0],[2,0,4,4,6,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[2,2,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[1,0,1,0,0,0],[2,8,1,1,1,2],[0,0,0,0,8,0],[0,0,0,0,0,0],[0,0,0,0,8,0],[0,0,0,0,8,0],[0,0,0,0,0,0],[0,0,0,0,8,0],[0,0,0,0,8,0],[0,0,0,0,8,0],[1,1,8,3,1,3],[2,1,2,2,2,2],[0,0,0,0,8,0],[8,2,8,2,0,8],[8,8,8,3,0,8],[8,2,8,2,2,2],[0,0,0,0,0,0],[8,1,2,2,0,2],[4,3,3,1,0,3],[8,1,8,2,0,2],[0,0,3,5,8,2],[9,2,3,9,-1,2],[3,2,1,2,3,2],[0,0,0,0,8,0],[0,0,9,0,9,0],[0,0,1,0,5,0],[1979,1987,1939,1928,1932,1970],[0,0,5,0,5,0],[0,0,4,0,5,0],[0,0,0,0,0,0],[0,0,4,0,4,0],[0,0,8,0,4,0],[0,0,5,0,5,0],[0,0,5,0,5,0],[0,0,0,0,2,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[1,1,3,2,1,3],[1,1,2,2,0,2],[2,3,0,1,8,2],[2,3,0,2,1,2],[1,2,0,1,8,2],[8,4,0,0,0,0],[1,1,0,9,0,0],[0,0,0,0,1,0],[2,2,0,1,8,2],[1,2,0,1,1,2],[2,3,0,1,8,2],[66247.5,13048.75,17063.75,7227,0,9033.75],[2,2,0,1,8,2],[8,2,0,1,8,2],[2,3,0,2,8,2],[2,3,0,1,1,2],[2,3,0,1,8,2],[66247.5,6022.5,0,0,0,9033.75],[2,2,0,1,8,2],[1,1,1,1,1,2],[2,9,0,2,2,2],[3,1,1,2,1,3],[3,1,2,2,2,2],[1,2,0,0,0,0],[1,1,0,0,0,0],[0,0,0,0,0,0],[1,1,1,1,1,1],[731,514,518,423,324,613],[3,3,0,0,0,0],[0,0,0,0,60,0],[0,0,0,0,60,0],[0,0,1,0,1,0],[0,4,4,0,0,2],[8,0,0,2,0,0],[1,3,2,2,0,1],[0,0,0,2,2,0],[4,1,5,5,0,3],[8,8,8,8,3,7],[1,2,1,2,0,2],[1,1,0,1,2,1],[0,0,0,0,2,0],[0,0,0,0,8,0],[0,0,0,0,8,0],[0,0,0,0,8,0],[8,1,8,2,0,8],[16,16,8,10,0,6],[0,0,0,0,8,0],[28,4,-1,-1,-1,-1],[0,0,-1,-1,-1,-1],[0,0,0,0,8,0],[0,0,0,0,8,0],[0,0,0,0,8,0],[0,0,0,0,8,0],[98,1,1,3,0,98],[9,9,1,3,0,98],[3,2,0,7,1,4],[38,7,38,22,39,29],[0,0,0,0,0,0],[0,0,0,0,0,0],[38,7,38,22,39,29],[1,1,1,1,1,1],[2,2,0,2,0,0],[2,2,0,2,0,0],[0,0,0,0,8,0],[1,2,0,9,0,0],[3,3,0,9,0,0],[0,0,1,2,1,0],[0,0,0,0,2,0],[0,0,0,0,3,0],[0,0,0,0,0,0],[3,2,0,1,2,2],[3,5,3,5,0,8],[3,1,0,0,0,0],[0,2,1,0,0,0],[1,1,1,1,1,1],[1,0,5,1,1,1],[2,2,0,0,0,0],[3,3,0,0,0,0],[0,0,2,0,2,0],[2,2,3,3,0,2],[75,40,40,20,40,75],[1,1,1,1,1,1],[8,4,2,3,0,2],[2,0,0,1,0,0],[0,2,1,0,0,3],[2,2,2,2,0,8],[1,1,1,1,0,1],[2,3,2,2,0,2],[1,3,3,2,3,2],[3,4,2,3,3,3],[2,1,1,2,1,1],[1,1,1,1,1,1],[1,2,0,0,0,0],[2,1,0,9,0,0],[0,0,0,0,0,0],[2,3,2,2,1,3],[2,3,2,2,1,3],[7,5,7,4,0,6],[1,2,2,2,1,1],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,2,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[8,8,8,2,0,4],[0,0,1,0,1,0],[6,1,6,3,1,8],[2,2,0,1,2,3],[3,4,3,2,0,8],[4,2,1,2,0,9],[4,0,4,4,4,4],[8,1,0,2,2,1],[3,4,8,3,0,8],[2,1,2,2,0,2],[2,4,8,2,0,8],[3,2,2,5,0,8],[3,5,4,5,0,8],[2,2,2,2,0,2],[8,1,8,4,0,8],[2,1,2,2,0,2],[2,2,8,8,0,8],[3,5,2,2,0,8],[2,1,2,2,0,2],[2,2,8,5,0,8],[2,2,8,5,0,8],[1,4,8,2,0,8],[3,4,8,2,0,8],[0,0,1,0,1,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[4,4,3,2,0,3],[2,2,0,0,0,0],[0,0,0,0,1,0],[2,3,3,3,1,2],[4,4,9,3,0,9],[8,2,8,2,0,8],[1,3,0,0,0,0],[0,0,3,0,4,0],[3,3,0,0,0,0],[1,1,1,1,1,1],[1,1,0,3,8,3],[2,2,0,2,2,2],[3,4,4,4,0,8],[3,3,0,4,3,3],[4,2,0,1,1,5],[2,2,0,3,1,3],[1,1,0,3,1,3],[5,1,5,5,2,2],[1,1,1,1,3,1],[4,4,4,4,1,4],[15,1,11,3,1,1],[1,1,0,2,0,0],[200902,201003,0,0,0,0],[1,3,0,0,0,0],[1,3,0,0,0,0],[2,8,-1,-1,-1,-1],[0,0,1,0,1,0],[1,1,1,1,2,1],[0,0,0,0,1,0],[55,45,-1,-1,-1,-1],[-1,-1,-1,-1,-1,-1],[2,4,-1,-1,-1,-1],[0,0,0,0,0,0],[0,0,0,0,0,0],[-1,-1,-1,-1,-1,-1],[0,0,0,0,0,0],[0,0,4,0,4,0],[0,0,0,0,0,0],[0,0,-1,-1,-1,-1],[2,2,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[1,2,3,4,5,6],[0,0,0,0,0,0],[0,1,0,1,2,0],[1,0,0,0,1,0],[3,4,4,5,0,8],[3,4,4,4,0,8],[2,3,3,2,8,1],[12,10,11,8,98,9],[21,11,13,8,98,9],[710,842,401,0,60,760],[8,1,2,5,0,2],[50,50,50,46,58,50],[0,0,0,0,2,0],[0,0,0,0,2,0],[0,0,0,0,1,0],[2,2,2,3,3,2],[0,0,0,0,1,0],[1,1,1,15,11,1],[0,0,0,0,2,0],[8,4,8,4,0,4],[8,4,8,7,0,4],[0,0,0,0,1,0],[0,0,0,0,1,0],[2,2,2,1,99,2],[0,0,0,0,0,0],[0,0,0,0,99,0],[0,0,0,0,2,0],[0,0,0,0,8,0],[2,2,2,2,1,2],[0,0,0,0,3,0],[0,0,0,0,2,0],[0.523287671232877,0.523287671232877,0.523287671232877,0.523287671232877,1,0.523287671232877],[0,0,0,0,0,0],[0,0,0,0,0,0],[1100,2190,9851,0,9510,8720],[2411,1229,8323,0,7122,7212],[1,1,1,1,1,1],[0,0,0,0,0,0],[0,0,0,0,0,0],[3,3,0,0,0,0],[3,3,0,0,0,0],[2,1,0,0,0,0],[8,4,0,0,0,0],[1,3,0,1,2,2],[2,4,1,1,0,8],[2,4,0,0,0,0],[3,5,1,1,0,8],[0,0,0,0,0,0],[2,2,0,0,0,0],[0,0,0,0,8,0],[8,4,8,3,0,8],[2,1,0,0,0,0],[8,1,2,2,0,2],[3,2,4,3,0,1],[0,0,8,0,2,0],[0,0,1,0,2,0],[0,0,2,0,2,0],[0,0,8,0,2,0],[0,0,1,0,2,0],[0,0,1,0,2,0],[0,0,8,0,3,0],[4,1,3,3,0,3],[1,3,3,3,0,3],[111,78,75,70,152,32],[5,2,0,0,0,0],[0,0,0,0,8,0],[3,6,6,0,98,8],[151,999,0,0,0,0],[8493,0,0,0,0,0],[8290,0,0,0,0,0],[0,0,0,0,0,0],[2,4,0,0,0,0],[785,999,0,0,0,0],[35,0,0,0,0,0],[3,3,4,3,0,3],[3,3,3,3,0,3],[3,3,1,3,0,3],[0,0,5,0,5,0],[5,5,3,2,1,5],[3,3,3,3,0,3],[26.7,-1,-1,-1,-1,-1],[1,1,0,9,0,0],[1,1,2,2,2,2],[2,2,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[2,3,3,1,0,2],[3,6,-1,-1,-1,-1],[1,3,3,3,3,3],[1,1,1,1,1,1],[12,6,-1,-1,-1,-1],[0,0,0,0,0,0],[1,1,0,0,0,0],[2,2,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,4,0],[0,0,0,0,8,0],[0,2,8,0,8,1],[3,0,0,2,0,0],[0,3,2,0,2,1],[3,0,0,2,0,0],[1,1,1,2,2,1],[0,2,2,0,2,1],[2,0,0,2,0,0],[0,1,3,0,2,1],[1,0,0,2,0,0],[0,1,1,0,8,1],[2,0,0,2,0,0],[0,1,1,0,2,1],[1,0,0,2,0,0],[1,1,8,2,8,1],[0,1,1,0,2,1],[1,0,0,3,0,0],[0,2,1,0,8,1],[1,0,0,1,0,0],[0,1,2,0,2,1],[1,0,0,2,0,0],[2,1,2,3,2,1],[1,2,1,2,2,1],[0,1,1,0,2,1],[1,0,0,2,0,0],[1,2,2,2,1,1],[2,2,8,2,8,1],[2,2,1,1,2,1],[0,1,3,0,2,1],[3,0,0,1,0,0],[2,2,2,3,0,5],[0,0,0,0,0,0],[0,0,0,0,5,0],[0,0,0,0,8,0],[4,3,4,3,0,3],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,8,0],[8,2,8,5,0,2],[0,0,0,0,0,0],[0,5,-1,0,-1,-1],[9991,9983,9999,9999,9999,9999],[20,0,-1,0,-1,-1],[2,4,0,3,2,1],[23,14,808,0,563,783],[0,0,0,0,1,0],[0,0,0,0,2,0],[31,22,70,79,75,39],[-1,-1,-1,-1,-1,-1],[-1,-1,-1,-1,-1,-1],[-1,-1,-1,-1,-1,-1],[-1,-1,-1,-1,-1,-1],[-1,-1,-1,-1,-1,-1],[-1,-1,-1,-1,73,-1],[-1,-1,-1,-1,-1,-1],[-1,-1,-1,-1,-1,-1],[-1,-1,-1,-1,-1,-1],[-1,-1,-1,-1,-1,-1],[-1,-1,-1,-1,-1,-1],[-1,-1,-1,-1,-1,-1],[-1,-1,-1,-1,-1,-1],[1,2,0,0,0,0],[0,0,0,0,76,0],[0,0,0,0,35,0],[2,2,0,9,0,0],[1,2,1,2,2,2],[2,0,2,0,0,0],[0,0,0,0,0,0],[3,3,4,3,0,8],[1,1,1,1,1,1],[2,1,0,0,0,0],[0,0,2,0,2,0],[2,0,0,0,0,0],[0,4,7,0,8,0],[8,18,97,2,98,8],[2,2,0,9,0,0],[2,2,0,0,0,0],[641,891,0,11,10,60],[5319,240,0,6210,6110,8719],[5122,2145,0,9211,6133,7136],[436,57,0,479,473,585],[31,64,0,23,40,45],[8,0,8,0,8,8],[4,3,0,1,1,2],[1,1,0,0,0,2],[4,3,-1,99,-1,-1],[6,5,-1,99,-1,-1],[2,2,0,0,0,0],[1,1,0,6,3,0],[27.5,86,-1,26.5,37.3,38.1],[2,2,0,2,1,1],[0,0,0,0,0,0],[8,8,8,1,0,8],[2,3,8,2,2,3],[6,6,6,3,3,6],[5,5,0,0,0,0],[1,3,-1,-1,-1,-1],[1,2,0,9,0,0],[1,1,2,1,0,2],[0,0,2,0,2,0],[2,2,0,2,2,2],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[2,1,0,2,2,8],[0,0,0,0,0,0],[0,0,0,0,8,0],[0,0,0,0,0,0],[0,0,0,0,8,0],[2,2,0,2,2,2],[2,4,4,2,0,8],[1,2,0,2,2,2],[0,0,0,0,0,0],[0,0,0,0,8,0],[0,0,0,0,0,0],[0,0,0,0,8,0],[2,2,0,1,2,2],[0,0,0,0,8,0],[3,2,8,2,3,3],[2,0,1,3,0,0],[2,2,3,4,0,8],[5,5,0,4,5,4],[2,2,0,2,1,2],[1,2,1,2,2,2],[1,8,2,4,0,8],[3,8,1,1,0,8],[3,6,2,2,2,6],[8,1,1,2,0,8],[4,4,1,3,0,3],[1,0,1,0,0,1],[0,1,1,1,0,1],[65,64,32,0,36,42],[0,0,0,0,0,0],[2,5,8,2,0,8],[3,3,0,0,0,0],[1,3,0,0,0,0],[2,4,0,0,0,0],[2,2,0,0,0,0],[8,2,8,2,0,8],[2,3,2,1,1,3],[1,1,1,1,0,1],[2,2,2,2,0,2],[1,1,1,1,0,2],[2,2,1,2,0,2],[3,1,2,1,2,2],[16,1,2,1,2,2],[0,0,0,2,0,0],[0,0,0,0,0,0],[1,1,1,1,1,1],[0,0,2,0,2,0],[1,1,1,1,0,1],[0,0,0,0,0,0],[0,0,0,0,1,0],[98,98,6,2,1,5],[42735,8417.5,11007.5,4662,0,5827.5],[42735,3885,0,0,0,5827.5],[2,2,2,2,1,2],[4,3,3,2,0,3],[4,2,3,3,0,3],[2,9,0,0,0,0],[2,2,2,2,2,2],[1,1,7,4,5,1],[1,1,1,1,1,1],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,2,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[2,1,0,9,0,0],[0,0,0,0,0,0],[1,2,2,2,1,2],[1,2,2,2,1,2],[1,1,1,1,1,1],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,2,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[1,1,1,1,1,1],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,2,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[2,4,2,2,1,4],[2,4,2,2,1,4],[0,0,0,0,0,0],[1,4,1,1,1,4],[1,9,1,2,1,3],[2,2,2,2,2,1],[2,4,2,2,8,3],[0,0,0,0,2,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,1,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[6,5,1,4,1,3],[1,1,1,1,8,1],[2,3,0,0,0,0],[1,1,1,1,1,1],[9,9,0,0,0,9],[0,0,2,0,2,0],[1,2,0,0,0,0],[21,7,0,0,0,9],[12,7,0,0,0,9],[2,4,8,1,1,3],[0,0,0,0,0,0],[1,1,1,1,1,1],[1,1,1,1,1,1],[2,2,0,0,0,0],[2,2,0,0,0,0],[2,2,0,0,0,0],[501,501,501,501,501,501],[9,9,9,9,9,9],[2,2,3,1,3,2],[2,3,0,0,0,2],[2,3,0,0,0,0],[1,2,1,2,1,2],[0,0,0,0,0,0],[0,0,0,0,8,0],[0,0,0,0,0,0],[2,3,8,8,0,8],[0,0,0,0,98,0],[0,0,0,0,0,0],[2,2,8,2,0,8],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,3,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[2,1,0,0,0,0],[0,0,0,0,4,0],[0,0,0,0,0,0],[76.40000000000001,85.09999999999999,29.8,-1,29.4,32.3],[1,-1,-1,-1,-1,1],[1,1,1,2,0,1],[2,4,-1,9,-1,-1],[3,3,0,9,0,0],[3,1,0,9,0,0],[3,1,0,9,0,0],[0,0,2,0,2,0],[2,3,5,10,6,11],[8008,8008,8008,8008,8008,8008],[3,1,0,0,0,0],[3,2,7,7,0,1],[3,1,3,7,0,3],[7,4,6,7,0,4],[3,5,2,4,0,3],[0,0,0,0,0,0],[1,1,1,2,1,1],[4,3,1,3,0,2],[0,0,0,3,0,0],[7,7,7,7,0,7],[0,0,0,0,60,0],[97,97,97,97,0,97],[0,0,0,0,1,0],[0,0,0,0,1,0],[-1,-1,-1,-1,-1,-1],[-1,-1,-1,-1,-1,-1],[0,0,0,0,60,0],[0,0,0,0,9510,0],[0,0,0,0,7122,0],[0,0,0,0,0,0],[0,0,1,0,2,0],[0,0,2,0,1,0],[0,0,2,0,1,0],[2,0,1,0,0,0],[0,0,8,0,1,0],[0,0,2,0,1,0],[0,0,2,0,2,0],[0,0,0,0,563,0],[0,0,0,0,36,0],[0,0,0,0,36,0],[0,0,0,0,1,0],[2,3,3,3,2,3],[-1,-1,-1,-1,29.4,-1],[1,3,0,0,0,0],[0,0,0,0,2,0],[0,0,0,0,8,0],[1,1,1,1,1,1],[0,0,0,0,0,0],[2,2,0,0,0,0],[2,2,0,0,0,0],[8,1,2,2,0,2],[2,1,2,2,0,2],[2,1,2,2,0,2],[2,1,2,2,0,2],[1,3,0,0,0,0],[2,1,0,0,0,0],[1,2,0,0,0,0],[0,0,1,0,2,0],[2,2,0,0,0,0],[0,0,0,0,0,0],[3,4,1,1,0,3],[8,1,8,2,0,3],[1,1,0,5,4,3],[0,0,0,0,8,0],[8,5,4,5,0,8],[0,0,0,0,8,0],[2,1,0,0,0,0],[6,98,1,2,0,5],[8,98,6,4,0,3],[2,2,0,0,0,0],[2,1,0,2,2,2],[1,8,3,1,0,8],[2,3,0,0,0,0],[2,1,0,0,0,0],[1,0,5,3,-1,4],[0,0,0,0,8,0],[0,0,0,0,8,0],[0,0,0,0,8,0],[1,1,0,2,2,1],[4,4,0,4,4,4],[-1,-1,-1,-1,0,-1],[1,0,1,1,1,1],[8,3,8,2,0,8],[2,3,0,0,0,0],[0,0,2,2,0,2],[2,1,0,2,0,2],[0,0,1,0,0,0],[2,2,1,2,3,2],[0,0,0,0,0,0],[0,0,0,0,1,0],[0,0,0,0,0,0],[1,3,1,2,2,1],[2,1,1,1,2,1],[8,2,8,2,0,3],[1,1,0,0,0,0],[0,0,2,2,0,2],[52,16,0,0,0,6],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[2,2,2,2,2,2],[2,2,2,2,2,2],[2,2,2,2,1,2],[2,2,2,2,2,2],[2,2,2,2,2,1],[1,1,1,1,2,2],[0,0,2,0,2,0],[2,1,0,0,0,0],[2,3,0,0,0,0],[1,2,0,0,0,0],[2,2,0,0,0,0],[2,2,0,0,0,0],[3,3,0,0,0,0],[2,2,0,0,0,0],[2,2,0,0,0,0],[2,4,0,0,0,0],[1,1,0,0,0,0],[3,3,0,0,0,0],[2,1,0,0,0,0],[0,4,0,0,0,0],[2,2,0,0,0,0],[4,6,4,7,0,3],[3,3,3,6,0,3],[1,1,9,0,-1,9],[1,1,9,0,-1,9],[9,1,9,0,-1,9],[0,1,9,0,-1,9],[1,1,9,0,-1,9],[1,1,9,1,-1,9],[0,0,9,1,-1,9],[0,1,9,1,-1,9],[1,1,9,0,-1,9],[1,1,9,0,-1,9],[6,9,99,3,-1,99],[4,4,4,7,0,2],[2,1,0,0,0,0],[2,1,0,0,0,0],[1,3,0,0,0,0],[3,3,0,2,3,2],[3,4,3,2,0,5],[2,1,2,0,2,2],[3,4,0,0,0,0],[1,1,0,0,0,0],[2,2,2,0,2,2],[1,1,5,5,5,4],[1,4,0,0,0,0],[5,5,0,0,0,0],[4,5,8,2,0,5],[0.842050334890791,0.463127684189935,0.463127684189935,0.463127684189935,0.92625536837987,0.463127684189935],[0.842050334890791,0.463127684189935,0.463127684189935,0.463127684189935,0.92625536837987,0.463127684189935],[0.870611687321478,0.478836428026813,0.478836428026813,0.478836428026813,0.957672856053625,0.478836428026813],[3,20,-1,-1,-1,-1],[0,-1,-1,-1,-1,-1],[0,0,1,0,1,0],[1,1,0,2,2,1],[1,1,1,1,1,1],[2010,2010,2010,2010,2010,2010],[3,0.75,-1,-1,-1,-1],[5,9,8,1,9,9],[\"-1\",\"-1\",\" \",\" \",\" \",\" \"],[\"20\",\"5\",\" \",\"0\",\" \",\" \"],[\"5\",\"5\",\"6\",\"0\",\"3\",\"6\"],[\"4\",\"1\",\"4\",\"4\",\"4\",\"1\"],[\"3\",\"20\",\" \",\" \",\" \",\" \"],[\"6\",\"9\",\" \",\"3\",\" \",\" \"],[\"3\",\"4\",\" \",\" \",\" \",\" \"],[\" \",\" \",\"1\",\" \",\"0\",\" \"],[-1,-1,-1,-1,1,-1],[0,0,3,5,8,2],[\"16\",\"16\",\"8\",\"10\",\"0\",\"6\"]],\"container\":\"<table class=\\\"display\\\">\\n  <thead>\\n    <tr>\\n      <th> <\\/th>\\n      <th>mar1<\\/th>\\n      <th>mar2<\\/th>\\n      <th>mar3<\\/th>\\n      <th>mar4<\\/th>\\n      <th>mar5<\\/th>\\n      <th>mar6<\\/th>\\n      <th>mar7<\\/th>\\n      <th>mar8<\\/th>\\n      <th>mar9<\\/th>\\n      <th>mar11<\\/th>\\n      <th>mar12<\\/th>\\n      <th>abany<\\/th>\\n      <th>abdefect<\\/th>\\n      <th>abhlth<\\/th>\\n      <th>abnomore<\\/th>\\n      <th>abpoor<\\/th>\\n      <th>abrape<\\/th>\\n      <th>absingle<\\/th>\\n      <th>acqntsex<\\/th>\\n      <th>adults<\\/th>\\n      <th>advfront<\\/th>\\n      <th>affrmact<\\/th>\\n      <th>age<\\/th>\\n      <th>aged<\\/th>\\n      <th>agekdbrn<\\/th>\\n      <th>astrolgy<\\/th>\\n      <th>astrosci<\\/th>\\n      <th>attend<\\/th>\\n      <th>away1<\\/th>\\n      <th>away11<\\/th>\\n      <th>away2<\\/th>\\n      <th>away3<\\/th>\\n      <th>away4<\\/th>\\n      <th>away5<\\/th>\\n      <th>away6<\\/th>\\n      <th>away7<\\/th>\\n      <th>babies<\\/th>\\n      <th>backpain<\\/th>\\n      <th>balneg<\\/th>\\n      <th>balpos<\\/th>\\n      <th>betrlang<\\/th>\\n      <th>bible<\\/th>\\n      <th>bigbang<\\/th>\\n      <th>bizbstgw<\\/th>\\n      <th>BIZBSTNK<\\/th>\\n      <th>bizbsttx<\\/th>\\n      <th>bizinfgw<\\/th>\\n      <th>BIZINFNK<\\/th>\\n      <th>bizinftx<\\/th>\\n      <th>biznuke<\\/th>\\n      <th>blkwhite<\\/th>\\n      <th>born<\\/th>\\n      <th>boyorgrl<\\/th>\\n      <th>busdecid<\\/th>\\n      <th>BUSGRN<\\/th>\\n      <th>cappun<\\/th>\\n      <th>caremost<\\/th>\\n      <th>carsgen<\\/th>\\n      <th>chemfree<\\/th>\\n      <th>chemgen<\\/th>\\n      <th>childs<\\/th>\\n      <th>chldidel<\\/th>\\n      <th>class<\\/th>\\n      <th>CLONING<\\/th>\\n      <th>closeblk<\\/th>\\n      <th>closewht<\\/th>\\n      <th>cohort<\\/th>\\n      <th>colath<\\/th>\\n      <th>colcom<\\/th>\\n      <th>coldeg1<\\/th>\\n      <th>colhomo<\\/th>\\n      <th>colmil<\\/th>\\n      <th>COLMSLM<\\/th>\\n      <th>colrac<\\/th>\\n      <th>colsci<\\/th>\\n      <th>colscinm<\\/th>\\n      <th>comorsci<\\/th>\\n      <th>comprend<\\/th>\\n      <th>compuse<\\/th>\\n      <th>conarmy<\\/th>\\n      <th>conbus<\\/th>\\n      <th>conclerg<\\/th>\\n      <th>condemnd<\\/th>\\n      <th>condom<\\/th>\\n      <th>condrift<\\/th>\\n      <th>coneduc<\\/th>\\n      <th>confed<\\/th>\\n      <th>confinan<\\/th>\\n      <th>coninc<\\/th>\\n      <th>conjudge<\\/th>\\n      <th>conlabor<\\/th>\\n      <th>conlegis<\\/th>\\n      <th>conmedic<\\/th>\\n      <th>conpress<\\/th>\\n      <th>conrinc<\\/th>\\n      <th>consci<\\/th>\\n      <th>CONSENT<\\/th>\\n      <th>contv<\\/th>\\n      <th>coop<\\/th>\\n      <th>courts<\\/th>\\n      <th>cowrkhlp<\\/th>\\n      <th>cowrkint<\\/th>\\n      <th>crack30<\\/th>\\n      <th>CSHUTYPE<\\/th>\\n      <th>dateintv<\\/th>\\n      <th>degree<\\/th>\\n      <th>denom<\\/th>\\n      <th>denom16<\\/th>\\n      <th>discaff<\\/th>\\n      <th>discaffm<\\/th>\\n      <th>discaffw<\\/th>\\n      <th>divlaw<\\/th>\\n      <th>divorce<\\/th>\\n      <th>drivless<\\/th>\\n      <th>dwelling<\\/th>\\n      <th>dwelown<\\/th>\\n      <th>earnrs<\\/th>\\n      <th>earthsun<\\/th>\\n      <th>ecoagree<\\/th>\\n      <th>ecobsttx<\\/th>\\n      <th>ecoinftx<\\/th>\\n      <th>econgrn<\\/th>\\n      <th>educ<\\/th>\\n      <th>electron<\\/th>\\n      <th>emailhr<\\/th>\\n      <th>emailmin<\\/th>\\n      <th>ENGAGRNK<\\/th>\\n      <th>ENGBSTNK<\\/th>\\n      <th>engnuke<\\/th>\\n      <th>ENHINFNK<\\/th>\\n      <th>ENPRBFAM<\\/th>\\n      <th>ENPRBUS<\\/th>\\n      <th>eqwlth<\\/th>\\n      <th>eth1<\\/th>\\n      <th>eth2<\\/th>\\n      <th>eth3<\\/th>\\n      <th>ethnic<\\/th>\\n      <th>ethnum<\\/th>\\n      <th>evcrack<\\/th>\\n      <th>evidu<\\/th>\\n      <th>evolved<\\/th>\\n      <th>evpaidsx<\\/th>\\n      <th>evstray<\\/th>\\n      <th>evwork<\\/th>\\n      <th>expdesgn<\\/th>\\n      <th>exptext<\\/th>\\n      <th>extinct<\\/th>\\n      <th>fair<\\/th>\\n      <th>FAIR5<\\/th>\\n      <th>fairearn<\\/th>\\n      <th>famdif16<\\/th>\\n      <th>famgen<\\/th>\\n      <th>family16<\\/th>\\n      <th>famvswk<\\/th>\\n      <th>famwkoff<\\/th>\\n      <th>fear<\\/th>\\n      <th>fechld<\\/th>\\n      <th>feelevel<\\/th>\\n      <th>feeused<\\/th>\\n      <th>fefam<\\/th>\\n      <th>fehire<\\/th>\\n      <th>fejobaff<\\/th>\\n      <th>fepol<\\/th>\\n      <th>fepres<\\/th>\\n      <th>fepresch<\\/th>\\n      <th>finalter<\\/th>\\n      <th>finrela<\\/th>\\n      <th>form<\\/th>\\n      <th>formwt<\\/th>\\n      <th>fringeok<\\/th>\\n      <th>frndsex<\\/th>\\n      <th>FUCITZN<\\/th>\\n      <th>fund<\\/th>\\n      <th>fund16<\\/th>\\n      <th>futenrgy<\\/th>\\n      <th>gender1<\\/th>\\n      <th>gender10<\\/th>\\n      <th>gender11<\\/th>\\n      <th>gender12<\\/th>\\n      <th>gender2<\\/th>\\n      <th>gender3<\\/th>\\n      <th>gender4<\\/th>\\n      <th>gender5<\\/th>\\n      <th>gender6<\\/th>\\n      <th>gender7<\\/th>\\n      <th>gender8<\\/th>\\n      <th>gender9<\\/th>\\n      <th>genegen<\\/th>\\n      <th>getahead<\\/th>\\n      <th>god<\\/th>\\n      <th>goodlife<\\/th>\\n      <th>govdook<\\/th>\\n      <th>goveqinc<\\/th>\\n      <th>granborn<\\/th>\\n      <th>grass<\\/th>\\n      <th>GRNCON<\\/th>\\n      <th>grndemo<\\/th>\\n      <th>grnecon<\\/th>\\n      <th>GRNEFFME<\\/th>\\n      <th>grnexagg<\\/th>\\n      <th>grngroup<\\/th>\\n      <th>grnintl<\\/th>\\n      <th>grnmoney<\\/th>\\n      <th>grnprice<\\/th>\\n      <th>grnprog<\\/th>\\n      <th>grnsign<\\/th>\\n      <th>grnsol<\\/th>\\n      <th>grntaxes<\\/th>\\n      <th>grwtharm<\\/th>\\n      <th>grwthelp<\\/th>\\n      <th>gunlaw<\\/th>\\n      <th>gwbiz<\\/th>\\n      <th>gwpol<\\/th>\\n      <th>gwsci<\\/th>\\n      <th>H2OLESS<\\/th>\\n      <th>handmove<\\/th>\\n      <th>hapmar<\\/th>\\n      <th>happy<\\/th>\\n      <th>harmgood<\\/th>\\n      <th>harmsgrn<\\/th>\\n      <th>haveinfo<\\/th>\\n      <th>health<\\/th>\\n      <th>health1<\\/th>\\n      <th>hefinfo<\\/th>\\n      <th>helpblk<\\/th>\\n      <th>helpful<\\/th>\\n      <th>HELPHARM<\\/th>\\n      <th>helpnot<\\/th>\\n      <th>helpoth<\\/th>\\n      <th>helppoor<\\/th>\\n      <th>helpsick<\\/th>\\n      <th>hhrace<\\/th>\\n      <th>hhtype<\\/th>\\n      <th>hhtype1<\\/th>\\n      <th>hispanic<\\/th>\\n      <th>hivtest<\\/th>\\n      <th>hivtest1<\\/th>\\n      <th>hivtest2<\\/th>\\n      <th>hlpequip<\\/th>\\n      <th>hlthdays<\\/th>\\n      <th>homosex<\\/th>\\n      <th>hompop<\\/th>\\n      <th>hotcore<\\/th>\\n      <th>hrs1<\\/th>\\n      <th>hrs2<\\/th>\\n      <th>hrsrelax<\\/th>\\n      <th>hsbio<\\/th>\\n      <th>hschem<\\/th>\\n      <th>hsmath<\\/th>\\n      <th>hsphys<\\/th>\\n      <th>hunt<\\/th>\\n      <th>huntbear<\\/th>\\n      <th>hurtatwk<\\/th>\\n      <th>hvylift<\\/th>\\n      <th>icecaps<\\/th>\\n      <th>icesheet<\\/th>\\n      <th>id<\\/th>\\n      <th>idu30<\\/th>\\n      <th>if04who<\\/th>\\n      <th>IF08WHO<\\/th>\\n      <th>ihlpgrn<\\/th>\\n      <th>impgrn<\\/th>\\n      <th>incom16<\\/th>\\n      <th>income<\\/th>\\n      <th>income06<\\/th>\\n      <th>indus80<\\/th>\\n      <th>indusgen<\\/th>\\n      <th>intage<\\/th>\\n      <th>INTECON<\\/th>\\n      <th>INTEDUC<\\/th>\\n      <th>INTENVIR<\\/th>\\n      <th>intethn<\\/th>\\n      <th>INTFARM<\\/th>\\n      <th>inthisp<\\/th>\\n      <th>INTINTL<\\/th>\\n      <th>intlblks<\\/th>\\n      <th>intlwhts<\\/th>\\n      <th>INTMED<\\/th>\\n      <th>INTMIL<\\/th>\\n      <th>intrace1<\\/th>\\n      <th>intrace2<\\/th>\\n      <th>intrace3<\\/th>\\n      <th>intrhome<\\/th>\\n      <th>INTSCI<\\/th>\\n      <th>intsex<\\/th>\\n      <th>INTSPACE<\\/th>\\n      <th>INTTECH<\\/th>\\n      <th>intyrs<\\/th>\\n      <th>inuit<\\/th>\\n      <th>inuitway<\\/th>\\n      <th>isco681<\\/th>\\n      <th>isco88<\\/th>\\n      <th>issp<\\/th>\\n      <th>jew<\\/th>\\n      <th>jew16<\\/th>\\n      <th>jobfind<\\/th>\\n      <th>jobfind1<\\/th>\\n      <th>joblose<\\/th>\\n      <th>jobsecok<\\/th>\\n      <th>kidssol<\\/th>\\n      <th>KNOWSOL<\\/th>\\n      <th>knowwhat<\\/th>\\n      <th>KNWCAUSE<\\/th>\\n      <th>knwpolar<\\/th>\\n      <th>laidoff<\\/th>\\n      <th>lasers<\\/th>\\n      <th>ldcgrn<\\/th>\\n      <th>learnnew<\\/th>\\n      <th>letdie1<\\/th>\\n      <th>letin1<\\/th>\\n      <th>libath<\\/th>\\n      <th>libcom<\\/th>\\n      <th>libhomo<\\/th>\\n      <th>libmil<\\/th>\\n      <th>LIBMSLM<\\/th>\\n      <th>librac<\\/th>\\n      <th>life<\\/th>\\n      <th>liveblks<\\/th>\\n      <th>livewhts<\\/th>\\n      <th>lngthinv<\\/th>\\n      <th>localnum<\\/th>\\n      <th>madeg<\\/th>\\n      <th>maeduc<\\/th>\\n      <th>maind80<\\/th>\\n      <th>maisc681<\\/th>\\n      <th>maisco88<\\/th>\\n      <th>majorcol<\\/th>\\n      <th>manvsemp<\\/th>\\n      <th>maocc80<\\/th>\\n      <th>mapres80<\\/th>\\n      <th>marasian<\\/th>\\n      <th>marblk<\\/th>\\n      <th>marhisp<\\/th>\\n      <th>marhomo<\\/th>\\n      <th>marital<\\/th>\\n      <th>marwht<\\/th>\\n      <th>masei<\\/th>\\n      <th>matesex<\\/th>\\n      <th>mawrkgrw<\\/th>\\n      <th>mawrkslf<\\/th>\\n      <th>medagrsc<\\/th>\\n      <th>medbstsc<\\/th>\\n      <th>medinfsc<\\/th>\\n      <th>meovrwrk<\\/th>\\n      <th>mntlhlth<\\/th>\\n      <th>mobile16<\\/th>\\n      <th>mode<\\/th>\\n      <th>moredays<\\/th>\\n      <th>MOREMPG<\\/th>\\n      <th>mustwork<\\/th>\\n      <th>myskills<\\/th>\\n      <th>NANOBEN<\\/th>\\n      <th>NANOHARM<\\/th>\\n      <th>nanoknw1<\\/th>\\n      <th>nanoknw2<\\/th>\\n      <th>nanotech<\\/th>\\n      <th>nanowill<\\/th>\\n      <th>nataid<\\/th>\\n      <th>nataidy<\\/th>\\n      <th>natarms<\\/th>\\n      <th>natarmsy<\\/th>\\n      <th>natchld<\\/th>\\n      <th>natcity<\\/th>\\n      <th>natcityy<\\/th>\\n      <th>natcrime<\\/th>\\n      <th>natcrimy<\\/th>\\n      <th>natdrug<\\/th>\\n      <th>natdrugy<\\/th>\\n      <th>nateduc<\\/th>\\n      <th>nateducy<\\/th>\\n      <th>NATENRGY<\\/th>\\n      <th>natenvir<\\/th>\\n      <th>natenviy<\\/th>\\n      <th>natfare<\\/th>\\n      <th>natfarey<\\/th>\\n      <th>natheal<\\/th>\\n      <th>nathealy<\\/th>\\n      <th>natmass<\\/th>\\n      <th>natpark<\\/th>\\n      <th>natrace<\\/th>\\n      <th>natracey<\\/th>\\n      <th>natroad<\\/th>\\n      <th>natsci<\\/th>\\n      <th>natsoc<\\/th>\\n      <th>natspac<\\/th>\\n      <th>natspacy<\\/th>\\n      <th>news<\\/th>\\n      <th>NEWSFRMY<\\/th>\\n      <th>newsfrom<\\/th>\\n      <th>nextgen<\\/th>\\n      <th>NOBUYGRN<\\/th>\\n      <th>noicecap<\\/th>\\n      <th>nosun<\\/th>\\n      <th>NUKEELEC<\\/th>\\n      <th>nukegen<\\/th>\\n      <th>numemps<\\/th>\\n      <th>nummen<\\/th>\\n      <th>numorg<\\/th>\\n      <th>numwomen<\\/th>\\n      <th>obey<\\/th>\\n      <th>occ80<\\/th>\\n      <th>odds1<\\/th>\\n      <th>odds2<\\/th>\\n      <th>old1<\\/th>\\n      <th>old10<\\/th>\\n      <th>old11<\\/th>\\n      <th>old12<\\/th>\\n      <th>old13<\\/th>\\n      <th>old14<\\/th>\\n      <th>old2<\\/th>\\n      <th>old3<\\/th>\\n      <th>old4<\\/th>\\n      <th>old5<\\/th>\\n      <th>old6<\\/th>\\n      <th>old7<\\/th>\\n      <th>old8<\\/th>\\n      <th>old9<\\/th>\\n      <th>opdevel<\\/th>\\n      <th>oth16<\\/th>\\n      <th>other<\\/th>\\n      <th>othersex<\\/th>\\n      <th>othlang<\\/th>\\n      <th>othlang1<\\/th>\\n      <th>othlang2<\\/th>\\n      <th>othssame<\\/th>\\n      <th>oversamp<\\/th>\\n      <th>overwork<\\/th>\\n      <th>owngun<\\/th>\\n      <th>ownstock<\\/th>\\n      <th>padeg<\\/th>\\n      <th>paeduc<\\/th>\\n      <th>paidsex<\\/th>\\n      <th>painarms<\\/th>\\n      <th>paind80<\\/th>\\n      <th>paisc681<\\/th>\\n      <th>paisco88<\\/th>\\n      <th>paocc80<\\/th>\\n      <th>papres80<\\/th>\\n      <th>parborn<\\/th>\\n      <th>parsol<\\/th>\\n      <th>partfull<\\/th>\\n      <th>partners<\\/th>\\n      <th>partnrs5<\\/th>\\n      <th>partteam<\\/th>\\n      <th>partyid<\\/th>\\n      <th>pasei<\\/th>\\n      <th>pawrkslf<\\/th>\\n      <th>penguins<\\/th>\\n      <th>PEOPGRN<\\/th>\\n      <th>permoral<\\/th>\\n      <th>phone<\\/th>\\n      <th>PHYEFFRT<\\/th>\\n      <th>physhlth<\\/th>\\n      <th>pikupsex<\\/th>\\n      <th>pillok<\\/th>\\n      <th>pistol<\\/th>\\n      <th>polabuse<\\/th>\\n      <th>polaryr1<\\/th>\\n      <th>polaryr2<\\/th>\\n      <th>polaryr3<\\/th>\\n      <th>polaryr4<\\/th>\\n      <th>polaryr5<\\/th>\\n      <th>polaryr6<\\/th>\\n      <th>polaryr7<\\/th>\\n      <th>polaryr8<\\/th>\\n      <th>polattak<\\/th>\\n      <th>polbstgw<\\/th>\\n      <th>POLBSTNK<\\/th>\\n      <th>polbstsc<\\/th>\\n      <th>polbsttx<\\/th>\\n      <th>polescap<\\/th>\\n      <th>polgreed<\\/th>\\n      <th>polhitok<\\/th>\\n      <th>polinfgw<\\/th>\\n      <th>POLINFNK<\\/th>\\n      <th>polinfsc<\\/th>\\n      <th>polinftx<\\/th>\\n      <th>polmurdr<\\/th>\\n      <th>polnuke<\\/th>\\n      <th>polviews<\\/th>\\n      <th>popespks<\\/th>\\n      <th>popgrwth<\\/th>\\n      <th>popular<\\/th>\\n      <th>pornlaw<\\/th>\\n      <th>postlife<\\/th>\\n      <th>postmat1<\\/th>\\n      <th>postmat2<\\/th>\\n      <th>pray<\\/th>\\n      <th>prayer<\\/th>\\n      <th>premarsx<\\/th>\\n      <th>pres04<\\/th>\\n      <th>PRES08<\\/th>\\n      <th>prestg80<\\/th>\\n      <th>preteen<\\/th>\\n      <th>privent<\\/th>\\n      <th>prodctiv<\\/th>\\n      <th>promtefr<\\/th>\\n      <th>promteok<\\/th>\\n      <th>proudemp<\\/th>\\n      <th>pubdecid<\\/th>\\n      <th>punsin<\\/th>\\n      <th>racdif1<\\/th>\\n      <th>racdif2<\\/th>\\n      <th>racdif3<\\/th>\\n      <th>racdif4<\\/th>\\n      <th>race<\\/th>\\n      <th>racecen1<\\/th>\\n      <th>racecen2<\\/th>\\n      <th>racecen3<\\/th>\\n      <th>raclive<\\/th>\\n      <th>racopen<\\/th>\\n      <th>racpres<\\/th>\\n      <th>racwork<\\/th>\\n      <th>radioact<\\/th>\\n      <th>rank<\\/th>\\n      <th>realinc<\\/th>\\n      <th>realrinc<\\/th>\\n      <th>reborn<\\/th>\\n      <th>recycle<\\/th>\\n      <th>REDCEHME<\\/th>\\n      <th>reg16<\\/th>\\n      <th>region<\\/th>\\n      <th>relactiv<\\/th>\\n      <th>relate1<\\/th>\\n      <th>relate10<\\/th>\\n      <th>relate11<\\/th>\\n      <th>relate12<\\/th>\\n      <th>relate2<\\/th>\\n      <th>relate3<\\/th>\\n      <th>relate4<\\/th>\\n      <th>relate5<\\/th>\\n      <th>relate6<\\/th>\\n      <th>relate7<\\/th>\\n      <th>relate8<\\/th>\\n      <th>relate9<\\/th>\\n      <th>relatsex<\\/th>\\n      <th>relbstsc<\\/th>\\n      <th>relexp<\\/th>\\n      <th>relexper<\\/th>\\n      <th>relhh1<\\/th>\\n      <th>relhh10<\\/th>\\n      <th>relhh11<\\/th>\\n      <th>relhh12<\\/th>\\n      <th>relhh2<\\/th>\\n      <th>relhh3<\\/th>\\n      <th>relhh4<\\/th>\\n      <th>relhh5<\\/th>\\n      <th>relhh6<\\/th>\\n      <th>relhh7<\\/th>\\n      <th>relhh8<\\/th>\\n      <th>relhh9<\\/th>\\n      <th>relhhd1<\\/th>\\n      <th>relhhd10<\\/th>\\n      <th>relhhd11<\\/th>\\n      <th>relhhd12<\\/th>\\n      <th>relhhd2<\\/th>\\n      <th>relhhd3<\\/th>\\n      <th>relhhd4<\\/th>\\n      <th>relhhd5<\\/th>\\n      <th>relhhd6<\\/th>\\n      <th>relhhd7<\\/th>\\n      <th>relhhd8<\\/th>\\n      <th>relhhd9<\\/th>\\n      <th>relig<\\/th>\\n      <th>relig16<\\/th>\\n      <th>relinfsc<\\/th>\\n      <th>reliten<\\/th>\\n      <th>rellife<\\/th>\\n      <th>relneg<\\/th>\\n      <th>relpersn<\\/th>\\n      <th>relsp1<\\/th>\\n      <th>relsp10<\\/th>\\n      <th>relsp11<\\/th>\\n      <th>relsp12<\\/th>\\n      <th>relsp2<\\/th>\\n      <th>relsp3<\\/th>\\n      <th>relsp4<\\/th>\\n      <th>relsp5<\\/th>\\n      <th>relsp6<\\/th>\\n      <th>relsp7<\\/th>\\n      <th>relsp8<\\/th>\\n      <th>relsp9<\\/th>\\n      <th>res16<\\/th>\\n      <th>RES2006<\\/th>\\n      <th>respect<\\/th>\\n      <th>respnum<\\/th>\\n      <th>richwork<\\/th>\\n      <th>rifle<\\/th>\\n      <th>rincblls<\\/th>\\n      <th>rincom06<\\/th>\\n      <th>rincome<\\/th>\\n      <th>rotapple<\\/th>\\n      <th>rowngun<\\/th>\\n      <th>rplace<\\/th>\\n      <th>rvisitor<\\/th>\\n      <th>safefrst<\\/th>\\n      <th>safehlth<\\/th>\\n      <th>safetywk<\\/th>\\n      <th>sampcode<\\/th>\\n      <th>sample<\\/th>\\n      <th>satfin<\\/th>\\n      <th>satjob<\\/th>\\n      <th>satjob1<\\/th>\\n      <th>savesoul<\\/th>\\n      <th>sciagrgw<\\/th>\\n      <th>scibnfts<\\/th>\\n      <th>scibstgw<\\/th>\\n      <th>scifaith<\\/th>\\n      <th>scifrom<\\/th>\\n      <th>SCIFROMY<\\/th>\\n      <th>scigrn<\\/th>\\n      <th>sciinfgo<\\/th>\\n      <th>sciinfgw<\\/th>\\n      <th>SCINEWS1<\\/th>\\n      <th>SCINEWS2<\\/th>\\n      <th>scinews3<\\/th>\\n      <th>scistudy<\\/th>\\n      <th>scitext<\\/th>\\n      <th>scmed<\\/th>\\n      <th>scpol<\\/th>\\n      <th>screlig<\\/th>\\n      <th>scresrch<\\/th>\\n      <th>sealevel<\\/th>\\n      <th>secondwk<\\/th>\\n      <th>seeksci<\\/th>\\n      <th>SEEKSCIY<\\/th>\\n      <th>sei<\\/th>\\n      <th>sex<\\/th>\\n      <th>sexeduc<\\/th>\\n      <th>sexfreq<\\/th>\\n      <th>SEXORNT<\\/th>\\n      <th>sexsex<\\/th>\\n      <th>sexsex5<\\/th>\\n      <th>shotgun<\\/th>\\n      <th>sibs<\\/th>\\n      <th>size<\\/th>\\n      <th>SLPPRBLM<\\/th>\\n      <th>socbar<\\/th>\\n      <th>socfrend<\\/th>\\n      <th>socommun<\\/th>\\n      <th>socrel<\\/th>\\n      <th>solarrev<\\/th>\\n      <th>spaneng<\\/th>\\n      <th>spanking<\\/th>\\n      <th>spanself<\\/th>\\n      <th>spdeg<\\/th>\\n      <th>spden<\\/th>\\n      <th>speduc<\\/th>\\n      <th>spevwork<\\/th>\\n      <th>spfund<\\/th>\\n      <th>sphrs1<\\/th>\\n      <th>sphrs2<\\/th>\\n      <th>spind80<\\/th>\\n      <th>spisc681<\\/th>\\n      <th>spisco88<\\/th>\\n      <th>spjew<\\/th>\\n      <th>spkath<\\/th>\\n      <th>spkcom<\\/th>\\n      <th>spkhomo<\\/th>\\n      <th>spklang<\\/th>\\n      <th>spkmil<\\/th>\\n      <th>SPKMSLM<\\/th>\\n      <th>spkrac<\\/th>\\n      <th>spocc80<\\/th>\\n      <th>spother<\\/th>\\n      <th>sppres80<\\/th>\\n      <th>sprel<\\/th>\\n      <th>sprtprsn<\\/th>\\n      <th>spsei<\\/th>\\n      <th>SPVTRFAIR<\\/th>\\n      <th>spwrkslf<\\/th>\\n      <th>spwrksta<\\/th>\\n      <th>srcbelt<\\/th>\\n      <th>stockops<\\/th>\\n      <th>stress<\\/th>\\n      <th>STRREDPG<\\/th>\\n      <th>suicide1<\\/th>\\n      <th>suicide2<\\/th>\\n      <th>suicide3<\\/th>\\n      <th>suicide4<\\/th>\\n      <th>supcares<\\/th>\\n      <th>supervis<\\/th>\\n      <th>suphelp<\\/th>\\n      <th>tax<\\/th>\\n      <th>teamsafe<\\/th>\\n      <th>teens<\\/th>\\n      <th>teensex<\\/th>\\n      <th>TEMPGEN1<\\/th>\\n      <th>thnkself<\\/th>\\n      <th>TOMATOES<\\/th>\\n      <th>toodifme<\\/th>\\n      <th>toofast<\\/th>\\n      <th>toofewwk<\\/th>\\n      <th>TOPPROB1<\\/th>\\n      <th>TOPPROB2<\\/th>\\n      <th>trdunion<\\/th>\\n      <th>trust<\\/th>\\n      <th>TRUST5<\\/th>\\n      <th>trustman<\\/th>\\n      <th>trynewjb<\\/th>\\n      <th>tvhours<\\/th>\\n      <th>txbiz<\\/th>\\n      <th>txeco<\\/th>\\n      <th>txpol<\\/th>\\n      <th>unemp<\\/th>\\n      <th>union<\\/th>\\n      <th>unrelat<\\/th>\\n      <th>USCITZN<\\/th>\\n      <th>USDOENUF<\\/th>\\n      <th>usedup<\\/th>\\n      <th>usewww<\\/th>\\n      <th>uswar<\\/th>\\n      <th>uswary<\\/th>\\n      <th>version<\\/th>\\n      <th>vetyears<\\/th>\\n      <th>viruses<\\/th>\\n      <th>visitors<\\/th>\\n      <th>vote04<\\/th>\\n      <th>VOTE08<\\/th>\\n      <th>watergen<\\/th>\\n      <th>waypaid<\\/th>\\n      <th>WEBMOB<\\/th>\\n      <th>weekswrk<\\/th>\\n      <th>where1<\\/th>\\n      <th>where11<\\/th>\\n      <th>where2<\\/th>\\n      <th>where3<\\/th>\\n      <th>where4<\\/th>\\n      <th>where5<\\/th>\\n      <th>where6<\\/th>\\n      <th>where7<\\/th>\\n      <th>whoelse1<\\/th>\\n      <th>whoelse2<\\/th>\\n      <th>whoelse3<\\/th>\\n      <th>whoelse4<\\/th>\\n      <th>whoelse5<\\/th>\\n      <th>whoelse6<\\/th>\\n      <th>widowed<\\/th>\\n      <th>wkageism<\\/th>\\n      <th>wkdecide<\\/th>\\n      <th>wkfreedm<\\/th>\\n      <th>wkharoth<\\/th>\\n      <th>wkharsex<\\/th>\\n      <th>wkpraise<\\/th>\\n      <th>wkracism<\\/th>\\n      <th>wksexism<\\/th>\\n      <th>wksmooth<\\/th>\\n      <th>wksub<\\/th>\\n      <th>wksubs<\\/th>\\n      <th>wksup<\\/th>\\n      <th>wksups<\\/th>\\n      <th>wkvsfam<\\/th>\\n      <th>wlthblks<\\/th>\\n      <th>wlthwhts<\\/th>\\n      <th>worda<\\/th>\\n      <th>wordb<\\/th>\\n      <th>wordc<\\/th>\\n      <th>wordd<\\/th>\\n      <th>worde<\\/th>\\n      <th>wordf<\\/th>\\n      <th>wordg<\\/th>\\n      <th>wordh<\\/th>\\n      <th>wordi<\\/th>\\n      <th>wordj<\\/th>\\n      <th>wordsum<\\/th>\\n      <th>workblks<\\/th>\\n      <th>workdiff<\\/th>\\n      <th>workfast<\\/th>\\n      <th>workfor<\\/th>\\n      <th>workhard<\\/th>\\n      <th>workwhts<\\/th>\\n      <th>wrkgovt<\\/th>\\n      <th>wrkhome<\\/th>\\n      <th>wrksched<\\/th>\\n      <th>wrkslf<\\/th>\\n      <th>wrkstat<\\/th>\\n      <th>wrktime<\\/th>\\n      <th>wrktype<\\/th>\\n      <th>wrkwayup<\\/th>\\n      <th>wtss<\\/th>\\n      <th>wtssall<\\/th>\\n      <th>wtssnr<\\/th>\\n      <th>wwwhr<\\/th>\\n      <th>wwwmin<\\/th>\\n      <th>xmarsex<\\/th>\\n      <th>xmovie<\\/th>\\n      <th>xnorcsiz<\\/th>\\n      <th>year<\\/th>\\n      <th>yearsjob<\\/th>\\n      <th>zodiac<\\/th>\\n      <th>sexual.orientation<\\/th>\\n      <th>sex.partners<\\/th>\\n      <th>political.orientation<\\/th>\\n      <th>religious.orientation<\\/th>\\n      <th>weekly.hours.on.internet<\\/th>\\n      <th>verbal.ability<\\/th>\\n      <th>work.from.home.frequency<\\/th>\\n      <th>fire.communist.teacher<\\/th>\\n      <th>currently.married<\\/th>\\n      <th>children<\\/th>\\n      <th>education<\\/th>\\n    <\\/tr>\\n  <\\/thead>\\n<\\/table>\",\"options\":{\"columnDefs\":[{\"className\":\"dt-right\",\"targets\":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,256,257,258,259,260,261,262,263,264,265,266,267,268,269,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,289,290,291,292,293,294,295,296,297,298,299,300,301,302,303,304,305,306,307,308,309,310,311,312,313,314,315,316,317,318,319,320,321,322,323,324,325,326,327,328,329,330,331,332,333,334,335,336,337,338,339,340,341,342,343,344,345,346,347,348,349,350,351,352,353,354,355,356,357,358,359,360,361,362,363,364,365,366,367,368,369,370,371,372,373,374,375,376,377,378,379,380,381,382,383,384,385,386,387,388,389,390,391,392,393,394,395,396,397,398,399,400,401,402,403,404,405,406,407,408,409,410,411,412,413,414,415,416,417,418,419,420,421,422,423,424,425,426,427,428,429,430,431,432,433,434,435,436,437,438,439,440,441,442,443,444,445,446,447,448,449,450,451,452,453,454,455,456,457,458,459,460,461,462,463,464,465,466,467,468,469,470,471,472,473,474,475,476,477,478,479,480,481,482,483,484,485,486,487,488,489,490,491,492,493,494,495,496,497,498,499,500,501,502,503,504,505,506,507,508,509,510,511,512,513,514,515,516,517,518,519,520,521,522,523,524,525,526,527,528,529,530,531,532,533,534,535,536,537,538,539,540,541,542,543,544,545,546,547,548,549,550,551,552,553,554,555,556,557,558,559,560,561,562,563,564,565,566,567,568,569,570,571,572,573,574,575,576,577,578,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,597,598,599,600,601,602,603,604,605,606,607,608,609,610,611,612,613,614,615,616,617,618,619,620,621,622,623,624,625,626,627,628,629,630,631,632,633,634,635,636,637,638,639,640,641,642,643,644,645,646,647,648,649,650,651,652,653,654,655,656,657,658,659,660,661,662,663,664,665,666,667,668,669,670,671,672,673,674,675,676,677,678,679,680,681,682,683,684,685,686,687,688,689,690,691,692,693,694,695,696,697,698,699,700,701,702,703,704,705,706,707,708,709,710,711,712,713,714,715,716,717,718,719,720,721,722,723,724,725,726,727,728,729,730,731,732,733,734,735,736,737,738,739,740,741,742,743,744,745,746,747,748,749,750,751,752,753,754,755,756,757,758,759,760,761,762,763,764,765,766,767,768,769,770,771,772,773,774,775,776,777,778,779,780,781,782,783,784,785,786,787,788,789,790,799,800]},{\"orderable\":false,\"targets\":0},{\"name\":\" \",\"targets\":0},{\"name\":\"mar1\",\"targets\":1},{\"name\":\"mar2\",\"targets\":2},{\"name\":\"mar3\",\"targets\":3},{\"name\":\"mar4\",\"targets\":4},{\"name\":\"mar5\",\"targets\":5},{\"name\":\"mar6\",\"targets\":6},{\"name\":\"mar7\",\"targets\":7},{\"name\":\"mar8\",\"targets\":8},{\"name\":\"mar9\",\"targets\":9},{\"name\":\"mar11\",\"targets\":10},{\"name\":\"mar12\",\"targets\":11},{\"name\":\"abany\",\"targets\":12},{\"name\":\"abdefect\",\"targets\":13},{\"name\":\"abhlth\",\"targets\":14},{\"name\":\"abnomore\",\"targets\":15},{\"name\":\"abpoor\",\"targets\":16},{\"name\":\"abrape\",\"targets\":17},{\"name\":\"absingle\",\"targets\":18},{\"name\":\"acqntsex\",\"targets\":19},{\"name\":\"adults\",\"targets\":20},{\"name\":\"advfront\",\"targets\":21},{\"name\":\"affrmact\",\"targets\":22},{\"name\":\"age\",\"targets\":23},{\"name\":\"aged\",\"targets\":24},{\"name\":\"agekdbrn\",\"targets\":25},{\"name\":\"astrolgy\",\"targets\":26},{\"name\":\"astrosci\",\"targets\":27},{\"name\":\"attend\",\"targets\":28},{\"name\":\"away1\",\"targets\":29},{\"name\":\"away11\",\"targets\":30},{\"name\":\"away2\",\"targets\":31},{\"name\":\"away3\",\"targets\":32},{\"name\":\"away4\",\"targets\":33},{\"name\":\"away5\",\"targets\":34},{\"name\":\"away6\",\"targets\":35},{\"name\":\"away7\",\"targets\":36},{\"name\":\"babies\",\"targets\":37},{\"name\":\"backpain\",\"targets\":38},{\"name\":\"balneg\",\"targets\":39},{\"name\":\"balpos\",\"targets\":40},{\"name\":\"betrlang\",\"targets\":41},{\"name\":\"bible\",\"targets\":42},{\"name\":\"bigbang\",\"targets\":43},{\"name\":\"bizbstgw\",\"targets\":44},{\"name\":\"BIZBSTNK\",\"targets\":45},{\"name\":\"bizbsttx\",\"targets\":46},{\"name\":\"bizinfgw\",\"targets\":47},{\"name\":\"BIZINFNK\",\"targets\":48},{\"name\":\"bizinftx\",\"targets\":49},{\"name\":\"biznuke\",\"targets\":50},{\"name\":\"blkwhite\",\"targets\":51},{\"name\":\"born\",\"targets\":52},{\"name\":\"boyorgrl\",\"targets\":53},{\"name\":\"busdecid\",\"targets\":54},{\"name\":\"BUSGRN\",\"targets\":55},{\"name\":\"cappun\",\"targets\":56},{\"name\":\"caremost\",\"targets\":57},{\"name\":\"carsgen\",\"targets\":58},{\"name\":\"chemfree\",\"targets\":59},{\"name\":\"chemgen\",\"targets\":60},{\"name\":\"childs\",\"targets\":61},{\"name\":\"chldidel\",\"targets\":62},{\"name\":\"class\",\"targets\":63},{\"name\":\"CLONING\",\"targets\":64},{\"name\":\"closeblk\",\"targets\":65},{\"name\":\"closewht\",\"targets\":66},{\"name\":\"cohort\",\"targets\":67},{\"name\":\"colath\",\"targets\":68},{\"name\":\"colcom\",\"targets\":69},{\"name\":\"coldeg1\",\"targets\":70},{\"name\":\"colhomo\",\"targets\":71},{\"name\":\"colmil\",\"targets\":72},{\"name\":\"COLMSLM\",\"targets\":73},{\"name\":\"colrac\",\"targets\":74},{\"name\":\"colsci\",\"targets\":75},{\"name\":\"colscinm\",\"targets\":76},{\"name\":\"comorsci\",\"targets\":77},{\"name\":\"comprend\",\"targets\":78},{\"name\":\"compuse\",\"targets\":79},{\"name\":\"conarmy\",\"targets\":80},{\"name\":\"conbus\",\"targets\":81},{\"name\":\"conclerg\",\"targets\":82},{\"name\":\"condemnd\",\"targets\":83},{\"name\":\"condom\",\"targets\":84},{\"name\":\"condrift\",\"targets\":85},{\"name\":\"coneduc\",\"targets\":86},{\"name\":\"confed\",\"targets\":87},{\"name\":\"confinan\",\"targets\":88},{\"name\":\"coninc\",\"targets\":89},{\"name\":\"conjudge\",\"targets\":90},{\"name\":\"conlabor\",\"targets\":91},{\"name\":\"conlegis\",\"targets\":92},{\"name\":\"conmedic\",\"targets\":93},{\"name\":\"conpress\",\"targets\":94},{\"name\":\"conrinc\",\"targets\":95},{\"name\":\"consci\",\"targets\":96},{\"name\":\"CONSENT\",\"targets\":97},{\"name\":\"contv\",\"targets\":98},{\"name\":\"coop\",\"targets\":99},{\"name\":\"courts\",\"targets\":100},{\"name\":\"cowrkhlp\",\"targets\":101},{\"name\":\"cowrkint\",\"targets\":102},{\"name\":\"crack30\",\"targets\":103},{\"name\":\"CSHUTYPE\",\"targets\":104},{\"name\":\"dateintv\",\"targets\":105},{\"name\":\"degree\",\"targets\":106},{\"name\":\"denom\",\"targets\":107},{\"name\":\"denom16\",\"targets\":108},{\"name\":\"discaff\",\"targets\":109},{\"name\":\"discaffm\",\"targets\":110},{\"name\":\"discaffw\",\"targets\":111},{\"name\":\"divlaw\",\"targets\":112},{\"name\":\"divorce\",\"targets\":113},{\"name\":\"drivless\",\"targets\":114},{\"name\":\"dwelling\",\"targets\":115},{\"name\":\"dwelown\",\"targets\":116},{\"name\":\"earnrs\",\"targets\":117},{\"name\":\"earthsun\",\"targets\":118},{\"name\":\"ecoagree\",\"targets\":119},{\"name\":\"ecobsttx\",\"targets\":120},{\"name\":\"ecoinftx\",\"targets\":121},{\"name\":\"econgrn\",\"targets\":122},{\"name\":\"educ\",\"targets\":123},{\"name\":\"electron\",\"targets\":124},{\"name\":\"emailhr\",\"targets\":125},{\"name\":\"emailmin\",\"targets\":126},{\"name\":\"ENGAGRNK\",\"targets\":127},{\"name\":\"ENGBSTNK\",\"targets\":128},{\"name\":\"engnuke\",\"targets\":129},{\"name\":\"ENHINFNK\",\"targets\":130},{\"name\":\"ENPRBFAM\",\"targets\":131},{\"name\":\"ENPRBUS\",\"targets\":132},{\"name\":\"eqwlth\",\"targets\":133},{\"name\":\"eth1\",\"targets\":134},{\"name\":\"eth2\",\"targets\":135},{\"name\":\"eth3\",\"targets\":136},{\"name\":\"ethnic\",\"targets\":137},{\"name\":\"ethnum\",\"targets\":138},{\"name\":\"evcrack\",\"targets\":139},{\"name\":\"evidu\",\"targets\":140},{\"name\":\"evolved\",\"targets\":141},{\"name\":\"evpaidsx\",\"targets\":142},{\"name\":\"evstray\",\"targets\":143},{\"name\":\"evwork\",\"targets\":144},{\"name\":\"expdesgn\",\"targets\":145},{\"name\":\"exptext\",\"targets\":146},{\"name\":\"extinct\",\"targets\":147},{\"name\":\"fair\",\"targets\":148},{\"name\":\"FAIR5\",\"targets\":149},{\"name\":\"fairearn\",\"targets\":150},{\"name\":\"famdif16\",\"targets\":151},{\"name\":\"famgen\",\"targets\":152},{\"name\":\"family16\",\"targets\":153},{\"name\":\"famvswk\",\"targets\":154},{\"name\":\"famwkoff\",\"targets\":155},{\"name\":\"fear\",\"targets\":156},{\"name\":\"fechld\",\"targets\":157},{\"name\":\"feelevel\",\"targets\":158},{\"name\":\"feeused\",\"targets\":159},{\"name\":\"fefam\",\"targets\":160},{\"name\":\"fehire\",\"targets\":161},{\"name\":\"fejobaff\",\"targets\":162},{\"name\":\"fepol\",\"targets\":163},{\"name\":\"fepres\",\"targets\":164},{\"name\":\"fepresch\",\"targets\":165},{\"name\":\"finalter\",\"targets\":166},{\"name\":\"finrela\",\"targets\":167},{\"name\":\"form\",\"targets\":168},{\"name\":\"formwt\",\"targets\":169},{\"name\":\"fringeok\",\"targets\":170},{\"name\":\"frndsex\",\"targets\":171},{\"name\":\"FUCITZN\",\"targets\":172},{\"name\":\"fund\",\"targets\":173},{\"name\":\"fund16\",\"targets\":174},{\"name\":\"futenrgy\",\"targets\":175},{\"name\":\"gender1\",\"targets\":176},{\"name\":\"gender10\",\"targets\":177},{\"name\":\"gender11\",\"targets\":178},{\"name\":\"gender12\",\"targets\":179},{\"name\":\"gender2\",\"targets\":180},{\"name\":\"gender3\",\"targets\":181},{\"name\":\"gender4\",\"targets\":182},{\"name\":\"gender5\",\"targets\":183},{\"name\":\"gender6\",\"targets\":184},{\"name\":\"gender7\",\"targets\":185},{\"name\":\"gender8\",\"targets\":186},{\"name\":\"gender9\",\"targets\":187},{\"name\":\"genegen\",\"targets\":188},{\"name\":\"getahead\",\"targets\":189},{\"name\":\"god\",\"targets\":190},{\"name\":\"goodlife\",\"targets\":191},{\"name\":\"govdook\",\"targets\":192},{\"name\":\"goveqinc\",\"targets\":193},{\"name\":\"granborn\",\"targets\":194},{\"name\":\"grass\",\"targets\":195},{\"name\":\"GRNCON\",\"targets\":196},{\"name\":\"grndemo\",\"targets\":197},{\"name\":\"grnecon\",\"targets\":198},{\"name\":\"GRNEFFME\",\"targets\":199},{\"name\":\"grnexagg\",\"targets\":200},{\"name\":\"grngroup\",\"targets\":201},{\"name\":\"grnintl\",\"targets\":202},{\"name\":\"grnmoney\",\"targets\":203},{\"name\":\"grnprice\",\"targets\":204},{\"name\":\"grnprog\",\"targets\":205},{\"name\":\"grnsign\",\"targets\":206},{\"name\":\"grnsol\",\"targets\":207},{\"name\":\"grntaxes\",\"targets\":208},{\"name\":\"grwtharm\",\"targets\":209},{\"name\":\"grwthelp\",\"targets\":210},{\"name\":\"gunlaw\",\"targets\":211},{\"name\":\"gwbiz\",\"targets\":212},{\"name\":\"gwpol\",\"targets\":213},{\"name\":\"gwsci\",\"targets\":214},{\"name\":\"H2OLESS\",\"targets\":215},{\"name\":\"handmove\",\"targets\":216},{\"name\":\"hapmar\",\"targets\":217},{\"name\":\"happy\",\"targets\":218},{\"name\":\"harmgood\",\"targets\":219},{\"name\":\"harmsgrn\",\"targets\":220},{\"name\":\"haveinfo\",\"targets\":221},{\"name\":\"health\",\"targets\":222},{\"name\":\"health1\",\"targets\":223},{\"name\":\"hefinfo\",\"targets\":224},{\"name\":\"helpblk\",\"targets\":225},{\"name\":\"helpful\",\"targets\":226},{\"name\":\"HELPHARM\",\"targets\":227},{\"name\":\"helpnot\",\"targets\":228},{\"name\":\"helpoth\",\"targets\":229},{\"name\":\"helppoor\",\"targets\":230},{\"name\":\"helpsick\",\"targets\":231},{\"name\":\"hhrace\",\"targets\":232},{\"name\":\"hhtype\",\"targets\":233},{\"name\":\"hhtype1\",\"targets\":234},{\"name\":\"hispanic\",\"targets\":235},{\"name\":\"hivtest\",\"targets\":236},{\"name\":\"hivtest1\",\"targets\":237},{\"name\":\"hivtest2\",\"targets\":238},{\"name\":\"hlpequip\",\"targets\":239},{\"name\":\"hlthdays\",\"targets\":240},{\"name\":\"homosex\",\"targets\":241},{\"name\":\"hompop\",\"targets\":242},{\"name\":\"hotcore\",\"targets\":243},{\"name\":\"hrs1\",\"targets\":244},{\"name\":\"hrs2\",\"targets\":245},{\"name\":\"hrsrelax\",\"targets\":246},{\"name\":\"hsbio\",\"targets\":247},{\"name\":\"hschem\",\"targets\":248},{\"name\":\"hsmath\",\"targets\":249},{\"name\":\"hsphys\",\"targets\":250},{\"name\":\"hunt\",\"targets\":251},{\"name\":\"huntbear\",\"targets\":252},{\"name\":\"hurtatwk\",\"targets\":253},{\"name\":\"hvylift\",\"targets\":254},{\"name\":\"icecaps\",\"targets\":255},{\"name\":\"icesheet\",\"targets\":256},{\"name\":\"id\",\"targets\":257},{\"name\":\"idu30\",\"targets\":258},{\"name\":\"if04who\",\"targets\":259},{\"name\":\"IF08WHO\",\"targets\":260},{\"name\":\"ihlpgrn\",\"targets\":261},{\"name\":\"impgrn\",\"targets\":262},{\"name\":\"incom16\",\"targets\":263},{\"name\":\"income\",\"targets\":264},{\"name\":\"income06\",\"targets\":265},{\"name\":\"indus80\",\"targets\":266},{\"name\":\"indusgen\",\"targets\":267},{\"name\":\"intage\",\"targets\":268},{\"name\":\"INTECON\",\"targets\":269},{\"name\":\"INTEDUC\",\"targets\":270},{\"name\":\"INTENVIR\",\"targets\":271},{\"name\":\"intethn\",\"targets\":272},{\"name\":\"INTFARM\",\"targets\":273},{\"name\":\"inthisp\",\"targets\":274},{\"name\":\"INTINTL\",\"targets\":275},{\"name\":\"intlblks\",\"targets\":276},{\"name\":\"intlwhts\",\"targets\":277},{\"name\":\"INTMED\",\"targets\":278},{\"name\":\"INTMIL\",\"targets\":279},{\"name\":\"intrace1\",\"targets\":280},{\"name\":\"intrace2\",\"targets\":281},{\"name\":\"intrace3\",\"targets\":282},{\"name\":\"intrhome\",\"targets\":283},{\"name\":\"INTSCI\",\"targets\":284},{\"name\":\"intsex\",\"targets\":285},{\"name\":\"INTSPACE\",\"targets\":286},{\"name\":\"INTTECH\",\"targets\":287},{\"name\":\"intyrs\",\"targets\":288},{\"name\":\"inuit\",\"targets\":289},{\"name\":\"inuitway\",\"targets\":290},{\"name\":\"isco681\",\"targets\":291},{\"name\":\"isco88\",\"targets\":292},{\"name\":\"issp\",\"targets\":293},{\"name\":\"jew\",\"targets\":294},{\"name\":\"jew16\",\"targets\":295},{\"name\":\"jobfind\",\"targets\":296},{\"name\":\"jobfind1\",\"targets\":297},{\"name\":\"joblose\",\"targets\":298},{\"name\":\"jobsecok\",\"targets\":299},{\"name\":\"kidssol\",\"targets\":300},{\"name\":\"KNOWSOL\",\"targets\":301},{\"name\":\"knowwhat\",\"targets\":302},{\"name\":\"KNWCAUSE\",\"targets\":303},{\"name\":\"knwpolar\",\"targets\":304},{\"name\":\"laidoff\",\"targets\":305},{\"name\":\"lasers\",\"targets\":306},{\"name\":\"ldcgrn\",\"targets\":307},{\"name\":\"learnnew\",\"targets\":308},{\"name\":\"letdie1\",\"targets\":309},{\"name\":\"letin1\",\"targets\":310},{\"name\":\"libath\",\"targets\":311},{\"name\":\"libcom\",\"targets\":312},{\"name\":\"libhomo\",\"targets\":313},{\"name\":\"libmil\",\"targets\":314},{\"name\":\"LIBMSLM\",\"targets\":315},{\"name\":\"librac\",\"targets\":316},{\"name\":\"life\",\"targets\":317},{\"name\":\"liveblks\",\"targets\":318},{\"name\":\"livewhts\",\"targets\":319},{\"name\":\"lngthinv\",\"targets\":320},{\"name\":\"localnum\",\"targets\":321},{\"name\":\"madeg\",\"targets\":322},{\"name\":\"maeduc\",\"targets\":323},{\"name\":\"maind80\",\"targets\":324},{\"name\":\"maisc681\",\"targets\":325},{\"name\":\"maisco88\",\"targets\":326},{\"name\":\"majorcol\",\"targets\":327},{\"name\":\"manvsemp\",\"targets\":328},{\"name\":\"maocc80\",\"targets\":329},{\"name\":\"mapres80\",\"targets\":330},{\"name\":\"marasian\",\"targets\":331},{\"name\":\"marblk\",\"targets\":332},{\"name\":\"marhisp\",\"targets\":333},{\"name\":\"marhomo\",\"targets\":334},{\"name\":\"marital\",\"targets\":335},{\"name\":\"marwht\",\"targets\":336},{\"name\":\"masei\",\"targets\":337},{\"name\":\"matesex\",\"targets\":338},{\"name\":\"mawrkgrw\",\"targets\":339},{\"name\":\"mawrkslf\",\"targets\":340},{\"name\":\"medagrsc\",\"targets\":341},{\"name\":\"medbstsc\",\"targets\":342},{\"name\":\"medinfsc\",\"targets\":343},{\"name\":\"meovrwrk\",\"targets\":344},{\"name\":\"mntlhlth\",\"targets\":345},{\"name\":\"mobile16\",\"targets\":346},{\"name\":\"mode\",\"targets\":347},{\"name\":\"moredays\",\"targets\":348},{\"name\":\"MOREMPG\",\"targets\":349},{\"name\":\"mustwork\",\"targets\":350},{\"name\":\"myskills\",\"targets\":351},{\"name\":\"NANOBEN\",\"targets\":352},{\"name\":\"NANOHARM\",\"targets\":353},{\"name\":\"nanoknw1\",\"targets\":354},{\"name\":\"nanoknw2\",\"targets\":355},{\"name\":\"nanotech\",\"targets\":356},{\"name\":\"nanowill\",\"targets\":357},{\"name\":\"nataid\",\"targets\":358},{\"name\":\"nataidy\",\"targets\":359},{\"name\":\"natarms\",\"targets\":360},{\"name\":\"natarmsy\",\"targets\":361},{\"name\":\"natchld\",\"targets\":362},{\"name\":\"natcity\",\"targets\":363},{\"name\":\"natcityy\",\"targets\":364},{\"name\":\"natcrime\",\"targets\":365},{\"name\":\"natcrimy\",\"targets\":366},{\"name\":\"natdrug\",\"targets\":367},{\"name\":\"natdrugy\",\"targets\":368},{\"name\":\"nateduc\",\"targets\":369},{\"name\":\"nateducy\",\"targets\":370},{\"name\":\"NATENRGY\",\"targets\":371},{\"name\":\"natenvir\",\"targets\":372},{\"name\":\"natenviy\",\"targets\":373},{\"name\":\"natfare\",\"targets\":374},{\"name\":\"natfarey\",\"targets\":375},{\"name\":\"natheal\",\"targets\":376},{\"name\":\"nathealy\",\"targets\":377},{\"name\":\"natmass\",\"targets\":378},{\"name\":\"natpark\",\"targets\":379},{\"name\":\"natrace\",\"targets\":380},{\"name\":\"natracey\",\"targets\":381},{\"name\":\"natroad\",\"targets\":382},{\"name\":\"natsci\",\"targets\":383},{\"name\":\"natsoc\",\"targets\":384},{\"name\":\"natspac\",\"targets\":385},{\"name\":\"natspacy\",\"targets\":386},{\"name\":\"news\",\"targets\":387},{\"name\":\"NEWSFRMY\",\"targets\":388},{\"name\":\"newsfrom\",\"targets\":389},{\"name\":\"nextgen\",\"targets\":390},{\"name\":\"NOBUYGRN\",\"targets\":391},{\"name\":\"noicecap\",\"targets\":392},{\"name\":\"nosun\",\"targets\":393},{\"name\":\"NUKEELEC\",\"targets\":394},{\"name\":\"nukegen\",\"targets\":395},{\"name\":\"numemps\",\"targets\":396},{\"name\":\"nummen\",\"targets\":397},{\"name\":\"numorg\",\"targets\":398},{\"name\":\"numwomen\",\"targets\":399},{\"name\":\"obey\",\"targets\":400},{\"name\":\"occ80\",\"targets\":401},{\"name\":\"odds1\",\"targets\":402},{\"name\":\"odds2\",\"targets\":403},{\"name\":\"old1\",\"targets\":404},{\"name\":\"old10\",\"targets\":405},{\"name\":\"old11\",\"targets\":406},{\"name\":\"old12\",\"targets\":407},{\"name\":\"old13\",\"targets\":408},{\"name\":\"old14\",\"targets\":409},{\"name\":\"old2\",\"targets\":410},{\"name\":\"old3\",\"targets\":411},{\"name\":\"old4\",\"targets\":412},{\"name\":\"old5\",\"targets\":413},{\"name\":\"old6\",\"targets\":414},{\"name\":\"old7\",\"targets\":415},{\"name\":\"old8\",\"targets\":416},{\"name\":\"old9\",\"targets\":417},{\"name\":\"opdevel\",\"targets\":418},{\"name\":\"oth16\",\"targets\":419},{\"name\":\"other\",\"targets\":420},{\"name\":\"othersex\",\"targets\":421},{\"name\":\"othlang\",\"targets\":422},{\"name\":\"othlang1\",\"targets\":423},{\"name\":\"othlang2\",\"targets\":424},{\"name\":\"othssame\",\"targets\":425},{\"name\":\"oversamp\",\"targets\":426},{\"name\":\"overwork\",\"targets\":427},{\"name\":\"owngun\",\"targets\":428},{\"name\":\"ownstock\",\"targets\":429},{\"name\":\"padeg\",\"targets\":430},{\"name\":\"paeduc\",\"targets\":431},{\"name\":\"paidsex\",\"targets\":432},{\"name\":\"painarms\",\"targets\":433},{\"name\":\"paind80\",\"targets\":434},{\"name\":\"paisc681\",\"targets\":435},{\"name\":\"paisco88\",\"targets\":436},{\"name\":\"paocc80\",\"targets\":437},{\"name\":\"papres80\",\"targets\":438},{\"name\":\"parborn\",\"targets\":439},{\"name\":\"parsol\",\"targets\":440},{\"name\":\"partfull\",\"targets\":441},{\"name\":\"partners\",\"targets\":442},{\"name\":\"partnrs5\",\"targets\":443},{\"name\":\"partteam\",\"targets\":444},{\"name\":\"partyid\",\"targets\":445},{\"name\":\"pasei\",\"targets\":446},{\"name\":\"pawrkslf\",\"targets\":447},{\"name\":\"penguins\",\"targets\":448},{\"name\":\"PEOPGRN\",\"targets\":449},{\"name\":\"permoral\",\"targets\":450},{\"name\":\"phone\",\"targets\":451},{\"name\":\"PHYEFFRT\",\"targets\":452},{\"name\":\"physhlth\",\"targets\":453},{\"name\":\"pikupsex\",\"targets\":454},{\"name\":\"pillok\",\"targets\":455},{\"name\":\"pistol\",\"targets\":456},{\"name\":\"polabuse\",\"targets\":457},{\"name\":\"polaryr1\",\"targets\":458},{\"name\":\"polaryr2\",\"targets\":459},{\"name\":\"polaryr3\",\"targets\":460},{\"name\":\"polaryr4\",\"targets\":461},{\"name\":\"polaryr5\",\"targets\":462},{\"name\":\"polaryr6\",\"targets\":463},{\"name\":\"polaryr7\",\"targets\":464},{\"name\":\"polaryr8\",\"targets\":465},{\"name\":\"polattak\",\"targets\":466},{\"name\":\"polbstgw\",\"targets\":467},{\"name\":\"POLBSTNK\",\"targets\":468},{\"name\":\"polbstsc\",\"targets\":469},{\"name\":\"polbsttx\",\"targets\":470},{\"name\":\"polescap\",\"targets\":471},{\"name\":\"polgreed\",\"targets\":472},{\"name\":\"polhitok\",\"targets\":473},{\"name\":\"polinfgw\",\"targets\":474},{\"name\":\"POLINFNK\",\"targets\":475},{\"name\":\"polinfsc\",\"targets\":476},{\"name\":\"polinftx\",\"targets\":477},{\"name\":\"polmurdr\",\"targets\":478},{\"name\":\"polnuke\",\"targets\":479},{\"name\":\"polviews\",\"targets\":480},{\"name\":\"popespks\",\"targets\":481},{\"name\":\"popgrwth\",\"targets\":482},{\"name\":\"popular\",\"targets\":483},{\"name\":\"pornlaw\",\"targets\":484},{\"name\":\"postlife\",\"targets\":485},{\"name\":\"postmat1\",\"targets\":486},{\"name\":\"postmat2\",\"targets\":487},{\"name\":\"pray\",\"targets\":488},{\"name\":\"prayer\",\"targets\":489},{\"name\":\"premarsx\",\"targets\":490},{\"name\":\"pres04\",\"targets\":491},{\"name\":\"PRES08\",\"targets\":492},{\"name\":\"prestg80\",\"targets\":493},{\"name\":\"preteen\",\"targets\":494},{\"name\":\"privent\",\"targets\":495},{\"name\":\"prodctiv\",\"targets\":496},{\"name\":\"promtefr\",\"targets\":497},{\"name\":\"promteok\",\"targets\":498},{\"name\":\"proudemp\",\"targets\":499},{\"name\":\"pubdecid\",\"targets\":500},{\"name\":\"punsin\",\"targets\":501},{\"name\":\"racdif1\",\"targets\":502},{\"name\":\"racdif2\",\"targets\":503},{\"name\":\"racdif3\",\"targets\":504},{\"name\":\"racdif4\",\"targets\":505},{\"name\":\"race\",\"targets\":506},{\"name\":\"racecen1\",\"targets\":507},{\"name\":\"racecen2\",\"targets\":508},{\"name\":\"racecen3\",\"targets\":509},{\"name\":\"raclive\",\"targets\":510},{\"name\":\"racopen\",\"targets\":511},{\"name\":\"racpres\",\"targets\":512},{\"name\":\"racwork\",\"targets\":513},{\"name\":\"radioact\",\"targets\":514},{\"name\":\"rank\",\"targets\":515},{\"name\":\"realinc\",\"targets\":516},{\"name\":\"realrinc\",\"targets\":517},{\"name\":\"reborn\",\"targets\":518},{\"name\":\"recycle\",\"targets\":519},{\"name\":\"REDCEHME\",\"targets\":520},{\"name\":\"reg16\",\"targets\":521},{\"name\":\"region\",\"targets\":522},{\"name\":\"relactiv\",\"targets\":523},{\"name\":\"relate1\",\"targets\":524},{\"name\":\"relate10\",\"targets\":525},{\"name\":\"relate11\",\"targets\":526},{\"name\":\"relate12\",\"targets\":527},{\"name\":\"relate2\",\"targets\":528},{\"name\":\"relate3\",\"targets\":529},{\"name\":\"relate4\",\"targets\":530},{\"name\":\"relate5\",\"targets\":531},{\"name\":\"relate6\",\"targets\":532},{\"name\":\"relate7\",\"targets\":533},{\"name\":\"relate8\",\"targets\":534},{\"name\":\"relate9\",\"targets\":535},{\"name\":\"relatsex\",\"targets\":536},{\"name\":\"relbstsc\",\"targets\":537},{\"name\":\"relexp\",\"targets\":538},{\"name\":\"relexper\",\"targets\":539},{\"name\":\"relhh1\",\"targets\":540},{\"name\":\"relhh10\",\"targets\":541},{\"name\":\"relhh11\",\"targets\":542},{\"name\":\"relhh12\",\"targets\":543},{\"name\":\"relhh2\",\"targets\":544},{\"name\":\"relhh3\",\"targets\":545},{\"name\":\"relhh4\",\"targets\":546},{\"name\":\"relhh5\",\"targets\":547},{\"name\":\"relhh6\",\"targets\":548},{\"name\":\"relhh7\",\"targets\":549},{\"name\":\"relhh8\",\"targets\":550},{\"name\":\"relhh9\",\"targets\":551},{\"name\":\"relhhd1\",\"targets\":552},{\"name\":\"relhhd10\",\"targets\":553},{\"name\":\"relhhd11\",\"targets\":554},{\"name\":\"relhhd12\",\"targets\":555},{\"name\":\"relhhd2\",\"targets\":556},{\"name\":\"relhhd3\",\"targets\":557},{\"name\":\"relhhd4\",\"targets\":558},{\"name\":\"relhhd5\",\"targets\":559},{\"name\":\"relhhd6\",\"targets\":560},{\"name\":\"relhhd7\",\"targets\":561},{\"name\":\"relhhd8\",\"targets\":562},{\"name\":\"relhhd9\",\"targets\":563},{\"name\":\"relig\",\"targets\":564},{\"name\":\"relig16\",\"targets\":565},{\"name\":\"relinfsc\",\"targets\":566},{\"name\":\"reliten\",\"targets\":567},{\"name\":\"rellife\",\"targets\":568},{\"name\":\"relneg\",\"targets\":569},{\"name\":\"relpersn\",\"targets\":570},{\"name\":\"relsp1\",\"targets\":571},{\"name\":\"relsp10\",\"targets\":572},{\"name\":\"relsp11\",\"targets\":573},{\"name\":\"relsp12\",\"targets\":574},{\"name\":\"relsp2\",\"targets\":575},{\"name\":\"relsp3\",\"targets\":576},{\"name\":\"relsp4\",\"targets\":577},{\"name\":\"relsp5\",\"targets\":578},{\"name\":\"relsp6\",\"targets\":579},{\"name\":\"relsp7\",\"targets\":580},{\"name\":\"relsp8\",\"targets\":581},{\"name\":\"relsp9\",\"targets\":582},{\"name\":\"res16\",\"targets\":583},{\"name\":\"RES2006\",\"targets\":584},{\"name\":\"respect\",\"targets\":585},{\"name\":\"respnum\",\"targets\":586},{\"name\":\"richwork\",\"targets\":587},{\"name\":\"rifle\",\"targets\":588},{\"name\":\"rincblls\",\"targets\":589},{\"name\":\"rincom06\",\"targets\":590},{\"name\":\"rincome\",\"targets\":591},{\"name\":\"rotapple\",\"targets\":592},{\"name\":\"rowngun\",\"targets\":593},{\"name\":\"rplace\",\"targets\":594},{\"name\":\"rvisitor\",\"targets\":595},{\"name\":\"safefrst\",\"targets\":596},{\"name\":\"safehlth\",\"targets\":597},{\"name\":\"safetywk\",\"targets\":598},{\"name\":\"sampcode\",\"targets\":599},{\"name\":\"sample\",\"targets\":600},{\"name\":\"satfin\",\"targets\":601},{\"name\":\"satjob\",\"targets\":602},{\"name\":\"satjob1\",\"targets\":603},{\"name\":\"savesoul\",\"targets\":604},{\"name\":\"sciagrgw\",\"targets\":605},{\"name\":\"scibnfts\",\"targets\":606},{\"name\":\"scibstgw\",\"targets\":607},{\"name\":\"scifaith\",\"targets\":608},{\"name\":\"scifrom\",\"targets\":609},{\"name\":\"SCIFROMY\",\"targets\":610},{\"name\":\"scigrn\",\"targets\":611},{\"name\":\"sciinfgo\",\"targets\":612},{\"name\":\"sciinfgw\",\"targets\":613},{\"name\":\"SCINEWS1\",\"targets\":614},{\"name\":\"SCINEWS2\",\"targets\":615},{\"name\":\"scinews3\",\"targets\":616},{\"name\":\"scistudy\",\"targets\":617},{\"name\":\"scitext\",\"targets\":618},{\"name\":\"scmed\",\"targets\":619},{\"name\":\"scpol\",\"targets\":620},{\"name\":\"screlig\",\"targets\":621},{\"name\":\"scresrch\",\"targets\":622},{\"name\":\"sealevel\",\"targets\":623},{\"name\":\"secondwk\",\"targets\":624},{\"name\":\"seeksci\",\"targets\":625},{\"name\":\"SEEKSCIY\",\"targets\":626},{\"name\":\"sei\",\"targets\":627},{\"name\":\"sex\",\"targets\":628},{\"name\":\"sexeduc\",\"targets\":629},{\"name\":\"sexfreq\",\"targets\":630},{\"name\":\"SEXORNT\",\"targets\":631},{\"name\":\"sexsex\",\"targets\":632},{\"name\":\"sexsex5\",\"targets\":633},{\"name\":\"shotgun\",\"targets\":634},{\"name\":\"sibs\",\"targets\":635},{\"name\":\"size\",\"targets\":636},{\"name\":\"SLPPRBLM\",\"targets\":637},{\"name\":\"socbar\",\"targets\":638},{\"name\":\"socfrend\",\"targets\":639},{\"name\":\"socommun\",\"targets\":640},{\"name\":\"socrel\",\"targets\":641},{\"name\":\"solarrev\",\"targets\":642},{\"name\":\"spaneng\",\"targets\":643},{\"name\":\"spanking\",\"targets\":644},{\"name\":\"spanself\",\"targets\":645},{\"name\":\"spdeg\",\"targets\":646},{\"name\":\"spden\",\"targets\":647},{\"name\":\"speduc\",\"targets\":648},{\"name\":\"spevwork\",\"targets\":649},{\"name\":\"spfund\",\"targets\":650},{\"name\":\"sphrs1\",\"targets\":651},{\"name\":\"sphrs2\",\"targets\":652},{\"name\":\"spind80\",\"targets\":653},{\"name\":\"spisc681\",\"targets\":654},{\"name\":\"spisco88\",\"targets\":655},{\"name\":\"spjew\",\"targets\":656},{\"name\":\"spkath\",\"targets\":657},{\"name\":\"spkcom\",\"targets\":658},{\"name\":\"spkhomo\",\"targets\":659},{\"name\":\"spklang\",\"targets\":660},{\"name\":\"spkmil\",\"targets\":661},{\"name\":\"SPKMSLM\",\"targets\":662},{\"name\":\"spkrac\",\"targets\":663},{\"name\":\"spocc80\",\"targets\":664},{\"name\":\"spother\",\"targets\":665},{\"name\":\"sppres80\",\"targets\":666},{\"name\":\"sprel\",\"targets\":667},{\"name\":\"sprtprsn\",\"targets\":668},{\"name\":\"spsei\",\"targets\":669},{\"name\":\"SPVTRFAIR\",\"targets\":670},{\"name\":\"spwrkslf\",\"targets\":671},{\"name\":\"spwrksta\",\"targets\":672},{\"name\":\"srcbelt\",\"targets\":673},{\"name\":\"stockops\",\"targets\":674},{\"name\":\"stress\",\"targets\":675},{\"name\":\"STRREDPG\",\"targets\":676},{\"name\":\"suicide1\",\"targets\":677},{\"name\":\"suicide2\",\"targets\":678},{\"name\":\"suicide3\",\"targets\":679},{\"name\":\"suicide4\",\"targets\":680},{\"name\":\"supcares\",\"targets\":681},{\"name\":\"supervis\",\"targets\":682},{\"name\":\"suphelp\",\"targets\":683},{\"name\":\"tax\",\"targets\":684},{\"name\":\"teamsafe\",\"targets\":685},{\"name\":\"teens\",\"targets\":686},{\"name\":\"teensex\",\"targets\":687},{\"name\":\"TEMPGEN1\",\"targets\":688},{\"name\":\"thnkself\",\"targets\":689},{\"name\":\"TOMATOES\",\"targets\":690},{\"name\":\"toodifme\",\"targets\":691},{\"name\":\"toofast\",\"targets\":692},{\"name\":\"toofewwk\",\"targets\":693},{\"name\":\"TOPPROB1\",\"targets\":694},{\"name\":\"TOPPROB2\",\"targets\":695},{\"name\":\"trdunion\",\"targets\":696},{\"name\":\"trust\",\"targets\":697},{\"name\":\"TRUST5\",\"targets\":698},{\"name\":\"trustman\",\"targets\":699},{\"name\":\"trynewjb\",\"targets\":700},{\"name\":\"tvhours\",\"targets\":701},{\"name\":\"txbiz\",\"targets\":702},{\"name\":\"txeco\",\"targets\":703},{\"name\":\"txpol\",\"targets\":704},{\"name\":\"unemp\",\"targets\":705},{\"name\":\"union\",\"targets\":706},{\"name\":\"unrelat\",\"targets\":707},{\"name\":\"USCITZN\",\"targets\":708},{\"name\":\"USDOENUF\",\"targets\":709},{\"name\":\"usedup\",\"targets\":710},{\"name\":\"usewww\",\"targets\":711},{\"name\":\"uswar\",\"targets\":712},{\"name\":\"uswary\",\"targets\":713},{\"name\":\"version\",\"targets\":714},{\"name\":\"vetyears\",\"targets\":715},{\"name\":\"viruses\",\"targets\":716},{\"name\":\"visitors\",\"targets\":717},{\"name\":\"vote04\",\"targets\":718},{\"name\":\"VOTE08\",\"targets\":719},{\"name\":\"watergen\",\"targets\":720},{\"name\":\"waypaid\",\"targets\":721},{\"name\":\"WEBMOB\",\"targets\":722},{\"name\":\"weekswrk\",\"targets\":723},{\"name\":\"where1\",\"targets\":724},{\"name\":\"where11\",\"targets\":725},{\"name\":\"where2\",\"targets\":726},{\"name\":\"where3\",\"targets\":727},{\"name\":\"where4\",\"targets\":728},{\"name\":\"where5\",\"targets\":729},{\"name\":\"where6\",\"targets\":730},{\"name\":\"where7\",\"targets\":731},{\"name\":\"whoelse1\",\"targets\":732},{\"name\":\"whoelse2\",\"targets\":733},{\"name\":\"whoelse3\",\"targets\":734},{\"name\":\"whoelse4\",\"targets\":735},{\"name\":\"whoelse5\",\"targets\":736},{\"name\":\"whoelse6\",\"targets\":737},{\"name\":\"widowed\",\"targets\":738},{\"name\":\"wkageism\",\"targets\":739},{\"name\":\"wkdecide\",\"targets\":740},{\"name\":\"wkfreedm\",\"targets\":741},{\"name\":\"wkharoth\",\"targets\":742},{\"name\":\"wkharsex\",\"targets\":743},{\"name\":\"wkpraise\",\"targets\":744},{\"name\":\"wkracism\",\"targets\":745},{\"name\":\"wksexism\",\"targets\":746},{\"name\":\"wksmooth\",\"targets\":747},{\"name\":\"wksub\",\"targets\":748},{\"name\":\"wksubs\",\"targets\":749},{\"name\":\"wksup\",\"targets\":750},{\"name\":\"wksups\",\"targets\":751},{\"name\":\"wkvsfam\",\"targets\":752},{\"name\":\"wlthblks\",\"targets\":753},{\"name\":\"wlthwhts\",\"targets\":754},{\"name\":\"worda\",\"targets\":755},{\"name\":\"wordb\",\"targets\":756},{\"name\":\"wordc\",\"targets\":757},{\"name\":\"wordd\",\"targets\":758},{\"name\":\"worde\",\"targets\":759},{\"name\":\"wordf\",\"targets\":760},{\"name\":\"wordg\",\"targets\":761},{\"name\":\"wordh\",\"targets\":762},{\"name\":\"wordi\",\"targets\":763},{\"name\":\"wordj\",\"targets\":764},{\"name\":\"wordsum\",\"targets\":765},{\"name\":\"workblks\",\"targets\":766},{\"name\":\"workdiff\",\"targets\":767},{\"name\":\"workfast\",\"targets\":768},{\"name\":\"workfor\",\"targets\":769},{\"name\":\"workhard\",\"targets\":770},{\"name\":\"workwhts\",\"targets\":771},{\"name\":\"wrkgovt\",\"targets\":772},{\"name\":\"wrkhome\",\"targets\":773},{\"name\":\"wrksched\",\"targets\":774},{\"name\":\"wrkslf\",\"targets\":775},{\"name\":\"wrkstat\",\"targets\":776},{\"name\":\"wrktime\",\"targets\":777},{\"name\":\"wrktype\",\"targets\":778},{\"name\":\"wrkwayup\",\"targets\":779},{\"name\":\"wtss\",\"targets\":780},{\"name\":\"wtssall\",\"targets\":781},{\"name\":\"wtssnr\",\"targets\":782},{\"name\":\"wwwhr\",\"targets\":783},{\"name\":\"wwwmin\",\"targets\":784},{\"name\":\"xmarsex\",\"targets\":785},{\"name\":\"xmovie\",\"targets\":786},{\"name\":\"xnorcsiz\",\"targets\":787},{\"name\":\"year\",\"targets\":788},{\"name\":\"yearsjob\",\"targets\":789},{\"name\":\"zodiac\",\"targets\":790},{\"name\":\"sexual.orientation\",\"targets\":791},{\"name\":\"sex.partners\",\"targets\":792},{\"name\":\"political.orientation\",\"targets\":793},{\"name\":\"religious.orientation\",\"targets\":794},{\"name\":\"weekly.hours.on.internet\",\"targets\":795},{\"name\":\"verbal.ability\",\"targets\":796},{\"name\":\"work.from.home.frequency\",\"targets\":797},{\"name\":\"fire.communist.teacher\",\"targets\":798},{\"name\":\"currently.married\",\"targets\":799},{\"name\":\"children\",\"targets\":800},{\"name\":\"education\",\"targets\":801}],\"order\":[],\"autoWidth\":false,\"orderClasses\":false}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n\n2.  Conduct the analysis described in the preregistration document\n\n<!-- -->\n\na.  The number of hours per week that a person spends on the Internet (\"WWWHR\") will\\\n    be predicted by their vocabulary (\"WORDSUM\"), age (\"AGE\"), sex (\"SEX\"), religiosity\\\n    (\"RELITEN\"), political orientation (\"POLVIEWS\"), and how often they work from home\\\n    (\"WRKHOME\").\n\n-   Let's use the `naniar` package's function `replace_with_na`to clean the data.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n### clean the data \n\ndata_pos <- data %>%\n  dplyr::select(wwwhr, wordsum, age, sex, reliten, polviews, wrkhome) %>%\nreplace_with_na(.,\n             replace = list(wwwhr = c(-1, 998, 999),\n                          wordsum = c(-1, 99),\n                          reliten = c(0, 8, 9), \n             polviews = c(0, 8, 9), \n             wrkhome = c(0,8,9), \n             age=c(0, 98, 99)))\n\ndata_pos |> \n  head() |> \n  DT::datatable()\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"datatables html-widget html-fill-item\" id=\"htmlwidget-f35aad2f66541b60094e\" style=\"width:100%;height:auto;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-f35aad2f66541b60094e\">{\"x\":{\"filter\":\"none\",\"vertical\":false,\"data\":[[\"1\",\"2\",\"3\",\"4\",\"5\",\"6\"],[3,20,null,null,null,null],[6,9,null,3,null,null],[31,23,71,82,78,40],[1,-1,-1,-1,-1,1],[1,4,1,1,1,4],[3,2,null,2,3,3],[3,4,null,null,null,null]],\"container\":\"<table class=\\\"display\\\">\\n  <thead>\\n    <tr>\\n      <th> <\\/th>\\n      <th>wwwhr<\\/th>\\n      <th>wordsum<\\/th>\\n      <th>age<\\/th>\\n      <th>sex<\\/th>\\n      <th>reliten<\\/th>\\n      <th>polviews<\\/th>\\n      <th>wrkhome<\\/th>\\n    <\\/tr>\\n  <\\/thead>\\n<\\/table>\",\"options\":{\"columnDefs\":[{\"className\":\"dt-right\",\"targets\":[1,2,3,4,5,6,7]},{\"orderable\":false,\"targets\":0},{\"name\":\" \",\"targets\":0},{\"name\":\"wwwhr\",\"targets\":1},{\"name\":\"wordsum\",\"targets\":2},{\"name\":\"age\",\"targets\":3},{\"name\":\"sex\",\"targets\":4},{\"name\":\"reliten\",\"targets\":5},{\"name\":\"polviews\",\"targets\":6},{\"name\":\"wrkhome\",\"targets\":7}],\"order\":[],\"autoWidth\":false,\"orderClasses\":false}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n\nQ: Can you explain what might be going on in the above code?\n\nA: *The `replace_with_na` function is replacing zeros with NAs*\n\nQ: The next step in data cleaning would be to ensure that the data in your code are aligned with the description/ usage context of the variables\n\n-   Recode sex and reliten as necessary\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata_pos <- data_pos |> \n  mutate(sex = factor(ifelse(sex == -1, \"Male\", \n                             ifelse(sex == 1, \"Female\", NA)), \n                      levels = c(\"Male\", \"Female\")),\n         reliten_recode = factor(reliten, levels = 1:5))\n```\n:::\n\n\n\n## Missingness\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata_pos %>%\n  dplyr::select(reliten, reliten_recode)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2,044 × 2\n   reliten reliten_recode\n     <dbl> <fct>         \n 1       1 1             \n 2       4 4             \n 3       1 1             \n 4       1 1             \n 5       1 1             \n 6       4 4             \n 7       3 3             \n 8       1 1             \n 9       1 1             \n10       1 1             \n# ℹ 2,034 more rows\n```\n\n\n:::\n\n```{.r .cell-code}\nskimr::skim(data_pos)\n```\n\n::: {.cell-output-display}\n\nTable: Data summary\n\n|                         |         |\n|:------------------------|:--------|\n|Name                     |data_pos |\n|Number of rows           |2044     |\n|Number of columns        |8        |\n|_______________________  |         |\n|Column type frequency:   |         |\n|factor                   |2        |\n|numeric                  |6        |\n|________________________ |         |\n|Group variables          |None     |\n\n\n**Variable type: factor**\n\n|skim_variable  | n_missing| complete_rate|ordered | n_unique|top_counts                     |\n|:--------------|---------:|-------------:|:-------|--------:|:------------------------------|\n|sex            |         0|          1.00|FALSE   |        2|Mal: 1153, Fem: 891            |\n|reliten_recode |        99|          0.95|FALSE   |        4|2: 747, 1: 707, 4: 363, 3: 128 |\n\n\n**Variable type: numeric**\n\n|skim_variable | n_missing| complete_rate|  mean|    sd| p0| p25| p50| p75| p100|hist  |\n|:-------------|---------:|-------------:|-----:|-----:|--:|---:|---:|---:|----:|:-----|\n|wwwhr         |       996|          0.51|  9.79| 13.41|  0|   2|   5|  14|  168|▇▁▁▁▁ |\n|wordsum       |       657|          0.68|  6.03|  2.07|  0|   5|   6|   7|   10|▁▃▇▅▂ |\n|age           |         3|          1.00| 47.97| 17.68| 18|  33|  47|  61|   89|▇▇▇▅▃ |\n|reliten       |        99|          0.95|  2.08|  1.08|  1|   1|   2|   3|    4|▇▇▁▂▃ |\n|polviews      |        71|          0.97|  4.08|  1.46|  1|   3|   4|   5|    7|▃▂▇▃▅ |\n|wrkhome       |       882|          0.57|  2.26|  1.72|  1|   1|   1|   4|    6|▇▁▁▂▁ |\n\n\n:::\n:::\n\n\n\n## Fit a Poisson model to the data.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npoisson_model <- glm(wwwhr ~ wordsum + age + sex + reliten+ polviews + wrkhome, \n                     data = data_pos, \n                     family = poisson(link = \"log\"))\n\nmodel_summary <- summary(poisson_model)$coefficients\nci <- confint(poisson_model)  # Compute confidence intervals\n\n# Create a tidy dataframe\neffects_table <- as.data.frame(model_summary) |> \n  tibble::rownames_to_column(var = \"Predictor\") |> \n  dplyr::mutate(\n    `Estimate` = round(Estimate, 3),\n    `Std. Error` = round(`Std. Error`, 3),\n    `z value` = round(`z value`, 3),\n    `Pr(>|z|)` = round(`Pr(>|z|)`, 3),\n    `CI Lower` = round(ci[,1], 3),\n    `CI Upper` = round(ci[,2], 3)\n  )\n\n# Display the table using kable\nkable(effects_table, format = \"markdown\", caption = \"Poisson Model Coefficients\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Poisson Model Coefficients\n\n|Predictor   | Estimate| Std. Error| z value| Pr(>&#124;z&#124;)| CI Lower| CI Upper|\n|:-----------|--------:|----------:|-------:|------------------:|--------:|--------:|\n|(Intercept) |    1.649|      0.082|  20.225|                  0|    1.489|    1.809|\n|wordsum     |    0.100|      0.008|  12.836|                  0|    0.084|    0.115|\n|age         |   -0.016|      0.001| -15.132|                  0|   -0.019|   -0.014|\n|sexFemale   |    0.259|      0.026|   9.836|                  0|    0.208|    0.311|\n|reliten     |    0.199|      0.012|  16.726|                  0|    0.176|    0.222|\n|polviews    |   -0.036|      0.010|  -3.666|                  0|   -0.054|   -0.017|\n|wrkhome     |    0.078|      0.008|  10.243|                  0|    0.063|    0.093|\n\n\n:::\n:::\n\n\n\n## Carry out model checking\n\nHint: performance package has the function you're looking for\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncheck_model(poisson_model,plot = T)\n```\n\n::: {.cell-output-display}\n![](poisson_lab_questions-1_files/figure-html/unnamed-chunk-7-1.png){width=1152}\n:::\n:::\n\n\n\n## Find any outliers\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Filter the data to remove outliers\ndata_pos_filtered <- data_pos %>%\n  mutate(mean_wwwhr = mean(wwwhr, na.rm = TRUE),\n         sd_wwwhr = sd(wwwhr, na.rm = TRUE)) %>%\n  filter(wwwhr >= (mean_wwwhr - 3 * sd_wwwhr) & wwwhr <= (mean_wwwhr + 3 * sd_wwwhr)) %>%\n  select(-mean_wwwhr, -sd_wwwhr)  # Remove the temporary columns\n\n\n\n\ncheck_outliers(poisson_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n3 outliers detected: cases 72, 156, 363.\n- Based on the following method and threshold: cook (0.9).\n- For variable: (Whole model).\n```\n\n\n:::\n:::\n\n\n\n## Refit the model after excluding outliers\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npoisson_model_filtered <- glm(wwwhr ~ wordsum + age + sex + reliten+ polviews + wrkhome, \n                     data = data_pos_filtered, \n                     family = poisson(link = \"log\"))\n\nmodel_summary <- summary(poisson_model_filtered)$coefficients\nci <- confint(poisson_model_filtered)  # Compute confidence intervals\n\n# Create a tidy dataframe\neffects_table <- as.data.frame(model_summary) |> \n  tibble::rownames_to_column(var = \"Predictor\") |> \n  dplyr::mutate(\n    `Estimate` = round(Estimate, 3),\n    `Std. Error` = round(`Std. Error`, 3),\n    `z value` = round(`z value`, 3),\n    `Pr(>|z|)` = round(`Pr(>|z|)`, 3),\n    `CI Lower` = round(ci[,1], 3),\n    `CI Upper` = round(ci[,2], 3)\n  )\n\n# Display the table using kable\nkable(effects_table, format = \"markdown\", caption = \"Poisson Model Coefficients (Excluding Outliers)\") \n```\n\n::: {.cell-output-display}\n\n\nTable: Poisson Model Coefficients (Excluding Outliers)\n\n|Predictor   | Estimate| Std. Error| z value| Pr(>&#124;z&#124;)| CI Lower| CI Upper|\n|:-----------|--------:|----------:|-------:|------------------:|--------:|--------:|\n|(Intercept) |    1.631|      0.086|  18.885|              0.000|    1.461|    1.800|\n|wordsum     |    0.091|      0.008|  11.002|              0.000|    0.075|    0.107|\n|age         |   -0.011|      0.001|  -9.705|              0.000|   -0.013|   -0.009|\n|sexFemale   |    0.142|      0.028|   5.071|              0.000|    0.087|    0.197|\n|reliten     |    0.143|      0.013|  11.254|              0.000|    0.118|    0.168|\n|polviews    |   -0.022|      0.010|  -2.118|              0.034|   -0.042|   -0.002|\n|wrkhome     |    0.040|      0.008|   4.758|              0.000|    0.023|    0.056|\n\n\n:::\n:::\n\n\n\n### Check for Overdispersion\n\nHint: performance package has the function you're looking for\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncheck_overdispersion(poisson_model_filtered)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# Overdispersion test\n\n       dispersion ratio =   10.684\n  Pearson's Chi-Squared = 6282.259\n                p-value =  < 0.001\n```\n\n\n:::\n:::\n\n\n\nWhat do you notice?\n\n> That we are expriencing overdispersion\n\nAnd what's a good next step forward?\n\n> We can deal with this using a Negative Binomial regression model instead of a Poisson model.\n\nCan there be another model class that can fit the data? If so, fit this model to the data.\n\n> A Negative Binomial regression model\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnb_model <- glm.nb(wwwhr ~ wordsum + age + sex + reliten_recode + polviews + wrkhome, \n                   data = data_pos_filtered)\n\nmodel_summary <- summary(nb_model)$coefficients\nci <- confint(nb_model)  # Compute confidence intervals\n\n# Create a tidy dataframe\neffects_table <- as.data.frame(model_summary) |> \n  tibble::rownames_to_column(var = \"Predictor\") |> \n  dplyr::mutate(\n    `Estimate` = round(Estimate, 3),\n    `Std. Error` = round(`Std. Error`, 3),\n    `z value` = round(`z value`, 3),\n    `Pr(>|z|)` = round(`Pr(>|z|)`, 3),\n    `CI Lower` = round(ci[,1], 3),\n    `CI Upper` = round(ci[,2], 3)\n  )\n\n# Display the table using kable\nkable(effects_table, format = \"markdown\", caption = \"Negative Binomial (Without Outliers)\") \n```\n\n::: {.cell-output-display}\n\n\nTable: Negative Binomial (Without Outliers)\n\n|Predictor       | Estimate| Std. Error| z value| Pr(>&#124;z&#124;)| CI Lower| CI Upper|\n|:---------------|--------:|----------:|-------:|------------------:|--------:|--------:|\n|(Intercept)     |    1.720|      0.252|   6.829|              0.000|    1.224|    2.221|\n|wordsum         |    0.101|      0.025|   3.972|              0.000|    0.049|    0.153|\n|age             |   -0.012|      0.003|  -3.608|              0.000|   -0.019|   -0.005|\n|sexFemale       |    0.105|      0.088|   1.201|              0.230|   -0.067|    0.278|\n|reliten_recode2 |    0.293|      0.106|   2.766|              0.006|    0.085|    0.500|\n|reliten_recode3 |    0.397|      0.200|   1.984|              0.047|    0.016|    0.806|\n|reliten_recode4 |    0.478|      0.125|   3.815|              0.000|    0.236|    0.721|\n|polviews        |   -0.024|      0.032|  -0.740|              0.460|   -0.086|    0.038|\n|wrkhome         |    0.035|      0.026|   1.330|              0.183|   -0.017|    0.089|\n\n\n:::\n:::\n\n\n\n## Which one is better- your earlier model, or later model?\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nAIC(poisson_model_filtered, nb_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                       df      AIC\npoisson_model_filtered  7 7136.602\nnb_model               10 3808.681\n```\n\n\n:::\n\n```{.r .cell-code}\n# Alternatively, you can compare the residual deviance and degrees of freedom:\ndeviance_poisson <- deviance(poisson_model_filtered)\ndf_poisson <- df.residual(poisson_model_filtered)\ndeviance_ratio_poisson <- deviance_poisson / df_poisson\n\n# Calculate deviance and degrees of freedom for Negative Binomial model\ndeviance_nb <- deviance(nb_model)\ndf_nb <- df.residual(nb_model)\ndeviance_ratio_nb <- deviance_nb / df_nb\n\n# Check for overdispersion and compare the models\nbetter_model <- ifelse(deviance_ratio_poisson > 1, \n                       \"Negative Binomial Model is better due to overdispersion\", \n                       ifelse(deviance_ratio_poisson > deviance_ratio_nb, \n                              \"Poisson Model is better\", \n                              \"Negative Binomial Model is better\"))\n\n# Print out the results\ncat(\"Deviance-to-DF Ratio for Poisson Model: \", deviance_ratio_poisson, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nDeviance-to-DF Ratio for Poisson Model:  8.721789 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Deviance-to-DF Ratio for Negative Binomial Model: \", deviance_ratio_nb, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nDeviance-to-DF Ratio for Negative Binomial Model:  1.129097 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Model Comparison: \", better_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nModel Comparison:  Negative Binomial Model is better due to overdispersion\n```\n\n\n:::\n:::\n\n\n\n> The Negative Binomial model has a much lower AIC (3808.681) compared to the Poisson model (7136.602), suggesting that the Negative Binomial model provides a better fit to the data.\n\n> Based on deviance, the negative binomial model is better.\n\n## What is zero inflation? Is there zero-inflation in your chosen model?\n\n> Zero-inflation occurs when the data contains an excess number of zero outcomes that cannot be explained by the underlying model, such as a Poisson or Negative Binomial model. In other words, there are more zero values in the data than expected given the distribution (Poisson or Negative Binomial), which can indicate that a separate process is generating these excess zeros.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nperformance::check_zeroinflation(nb_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# Check for zero-inflation\n\n   Observed zeros: 40\n  Predicted zeros: 63\n            Ratio: 1.57\n```\n\n\n:::\n:::\n\n\n\n## Log Lambda\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlambda_poisson <- predict(poisson_model_filtered, type = \"response\")\nlambda_nb <- predict(nb_model, type = \"response\")\n\n# Log transform the lambda values\nlog_lambda_poisson <- log(lambda_poisson)\nlog_lambda_nb <- log(lambda_nb)\n\n# Output the log lambda values for a subset of the data\nhead(data.frame(log_lambda_poisson, log_lambda_nb))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   log_lambda_poisson log_lambda_nb\n1            2.171034      2.079081\n2            2.881145      2.913070\n4            2.115022      2.220856\n8            2.191091      2.252398\n9            1.992306      2.030755\n12           2.578640      2.592963\n```\n\n\n:::\n:::\n\n\n\n## Mean Count\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npredicted_counts_poisson <- predict(poisson_model_filtered, type = \"response\")\npredicted_counts_nb <- predict(nb_model, type = \"response\")\n\n# Calculate the mean of predicted counts for each model\nmean_count_poisson <- mean(predicted_counts_poisson, na.rm = TRUE)\nmean_count_nb <- mean(predicted_counts_nb, na.rm = TRUE)\n\n# Output the mean counts\ncat(\"Mean Count (Poisson Model): \", mean_count_poisson, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMean Count (Poisson Model):  8.821849 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Mean Count (Negative Binomial Model): \", mean_count_nb, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMean Count (Negative Binomial Model):  8.836638 \n```\n\n\n:::\n:::\n\n\n\n## Report your conclusions\n\n> These results show that, on average, both models predict almost the same number of hours, with the Negative Binomial model giving a slightly higher estimate. This small difference could reflect model nuances, but both models suggest a similar central tendency in internet usage.\n",
    "supporting": [
      "poisson_lab_questions-1_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../site_libs/htmltools-fill-0.5.8.1/fill.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/htmlwidgets-1.6.4/htmlwidgets.js\"></script>\n<link href=\"../../site_libs/datatables-css-0.0.0/datatables-crosstalk.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/datatables-binding-0.33/datatables.js\"></script>\n<script src=\"../../site_libs/jquery-3.6.0/jquery-3.6.0.min.js\"></script>\n<link href=\"../../site_libs/dt-core-1.13.6/css/jquery.dataTables.min.css\" rel=\"stylesheet\" />\n<link href=\"../../site_libs/dt-core-1.13.6/css/jquery.dataTables.extra.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/dt-core-1.13.6/js/jquery.dataTables.min.js\"></script>\n<link href=\"../../site_libs/crosstalk-1.2.1/css/crosstalk.min.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/crosstalk-1.2.1/js/crosstalk.min.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}